apiVersion: v1
data:
  TYK_AUTH: YWU4MjExMWY3ZDczNDQ3MjUxYjY5ZTFlZWE3NGMxNzY=
  TYK_MODE: cHJv
  TYK_ORG: NjYyOThlMWE2MzBiNTEwMDAxMTVhNjdj
  TYK_URL: aHR0cDovL2Rhc2hib2FyZC1zdmMtdHlrLWNvbnRyb2wtcGxhbmUtdHlrLWRhc2hib2FyZC50eWstY3Auc3ZjOjMwMDA=
kind: Secret
metadata:
  name: tyk-operator-conf
  namespace: tyk-operator-system
type: Opaque