apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-operator-system
  project: infrastructure
  source:
    chart: tyk-operator
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 0.17.0
  syncPolicy:
    automated:
      prune: true