apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-oss-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: tyk-oss
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.4.0
    helm:
      parameters:
      - name: "image.tag"
        value: "6.2.13"
  syncPolicy:
    automated: 
      prune: true
  ignoreDifferences:
  - kind: PersistentVolumeClaim
    group: v1