apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-oss
  project: infrastructure
  source:
    chart: tyk-oss
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.3.0
    helm:
      parameters:
      - name: global.secrets.useSecretName
        value: my-secrets
      
      # set this for bitnamic redis
      #- name: global.redis.addrs[0]
      #  value: tyk-redis-master.redis.svc:6379
      
      # set this for bitnami redis-cluster
      - name: global.redis.addrs[0]
        value: tyk-redis-cluster.redis-cluster.svc:6379
      - name: global.redis.enableCluster
        value: "true"
      - name: global.redis.useSSL
        value: "true"
      - name: global.redis.sslInsecureSkipVerify
        value: "false"
      - name: global.redis.tlsMinVersion
        value: "1.2"
      - name: global.redis.tlsMaxVersion
        value: "1.3"
      - name: global.redis.secretName
        value: "redis-cluster-tls"
      - name: global.redis.certificatesMountPath
        value: "/etc/ssl/certs"
      - name: global.redis.sslCAFile
        value: "/etc/ssl/certs/ca.crt"
      - name: global.redis.sslCertFile
        value: "/etc/ssl/certs/tls.crt"
      - name: global.redis.sslKeyFile
        value: "/etc/ssl/certs/tls.key"
      - name: global.redis.volumeName
        value: "ca-cert"

      - name: global.redis.passSecret.name
        value: redis-password-secret
      - name: global.redis.passSecret.keyName
        value: redis-password
      - name: tyk-gateway.gateway.ingress.enabled
        value: "true"
      - name: tyk-gateway.gateway.ingress.className
        value: nginx
      #- name: 'tyk-gateway.gateway.ingress.annotations.cert-manager\.io\/cluster-issuer'
      #  value: selfsigned
      - name: 'tyk-gateway.gateway.ingress.annotations.cert-manager\.io\/issuer'
        value: letsencrypt-nginx
      - name: tyk-gateway.gateway.ingress.hosts[0].host
        value: "tyk-gw.157.245.30.155.nip.io"
      - name: tyk-gateway.gateway.ingress.hosts[0].paths[0].path
        value: /
      - name: tyk-gateway.gateway.ingress.hosts[0].paths[0].pathType
        value: ImplementationSpecific
      - name: tyk-gateway.gateway.ingress.tls[0].secretName
        value: letsencrypt-nginx # < cert-manager will store the created certificate in this secret.
      - name: tyk-gateway.gateway.ingress.tls[0].hosts[0]
        value: "tyk-gw.157.245.30.155.nip.io"
  syncPolicy:
    automated:
      prune: true