apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-oss
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-oss
  project: infrastructure
  source:
    chart: tyk-oss
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.3.0
    helm:
      valuesObject:
        global:
          secrets:
            # APISecret: CHANGEME
            useSecretName: my-secrets
          redis:
            addrs:
              - redis-cluster.redis-cluster.svc:6379
            # pass: ""
            passSecret:
              name: "redis-password-secret"
              keyName: "redis-password-secret"
            useSSL: "true"
            sslInsecureSkipVerify: "false"
            sslCAFile: "/etc/ssl/certs/ca.crt"
            certificatesMountPath: "/etc/ssl/certs"
            sslCertFile: "/etc/ssl/certs/tls.crt"
            sslKeyFile: "/etc/ssl/certs/tls.key"
            tlsMinVersion: "1.2"
            tlsMaxVersion: "1.3"
            secretName: "redis-cluster-tls"
            volumeName: "ca-cert"
            enableCluster: "true"
            # enableSentinel: false
            # sentinelPass: ""
            # masterName: ""
        tyk-gateway:
          gateway:
            ingress:
              enabled: "true"
              className: "nginx"
              annotations:
                cert-manager.io/issuer: letsencrypt-nginx
              hosts:
                - host: "tyk-gw.157.245.30.155.nip.io"
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: letsencrypt-nginx
                  hosts: 
                    - "tyk-gw.157.245.30.155.nip.io"
  syncPolicy:
    automated:
      prune: true