apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-oss
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-oss
  project: infrastructure
  source:
    chart: tyk-oss
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.3.0
    helm:
      parameters:
      - name: global.secrets.useSecretName
        value: my-secrets
      - name: global.redis.addrs
        value: tyk-redis-master.redis.svc:6379
      - name: global.redis.passSecret.name
        value: redis-password-secret
      - name: global.redis.passSecret.keyName
        value: redis-password
      - name: tyk-gateway.gateway.ingress.enabled
        value: "true"
      - name: tyk-gateway.gateway.ingress.className
        value: nginx
#      - name: tyk-gateway.gateway.ingress.annotations.cert-manager.io/issuer
#        value: letsencrypt-nginx
      - name: tyk-gateway.gateway.ingress.hosts[0].host
        value: tyk-gw.67-207-68-96.org
      - name: tyk-gateway.gateway.ingress.hosts[0].paths[0].path
        value: /
      - name: tyk-gateway.gateway.ingress.hosts[0].paths[0].pathType
        value: ImplementationSpecific
#      - name: tyk-gateway.gateway.ingress.tls[0].secretName
#        value: letsencrypt-nginx
#      - name: tyk-gateway.gateway.ingress.tls[0].hosts[0]
#        value: tyk-gw.67-207-68-96.org
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false