resources:
- ../base/
- tyk-hybrid-stg-sealedsecrets.yaml

patches:
  - target:
      kind: Application
      name: tyk-hybrid-dp
    patch: |-
      - op: "replace"
        path: "/spec/source/helm/valuesObject/global/remoteControlPlane/connectionString"
        value: "rural-gander-hyb.aws-euw2.cloud-ara.tyk.io:443"
      - op: "replace"
        path: "/metadata/name"
        value: "tyk-hybrid-dp-stg"
      - op: "replace"
        path: "/spec/source/helm/valuesObject/global/redis/addrs"
        value: 
          - "redis-hybrid-dp-stg-master:6379"
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/ingress/hosts"
        value: 
          - host: "jupiter-stg.org"
            paths:
              - path: /
                pathType: ImplementationSpecific
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/ingress/tls"
        value: 
          - secretName: letsencrypt-nginx
            hosts:
              - "jupiter-stg.org"
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/sharding/enabled"
        value: "true"
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/sharding/tags"
        value: "staging"
  - target:
      kind: Application
      name: redis-hybrid-dp
    patch: |-
      - op: "replace"
        path: "/metadata/name"
        value: "redis-hybrid-dp-stg"
  - target:
      kind: Application
    patch: |-
      - op: "replace"
        path: "/spec/destination/namespace"
        value: "tyk-hybrid-stg"
  - target:
      kind: OperatorContext
    patch: |-
      - op: "replace"
        path: "/spec/secretRef/namespace"
        value: "tyk-hybrid-stg"