---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-stack-postgres
spec:
  encryptedData:
    postgres-password: AgAkwAlMOg1lEQXJMRZTU1XjSZ1IsjwCuFci/lowlehKx+Qc/rNvPqPa45yTLHEscDsSGHUCWIL6VL95kRPIR9uS6O/rKxSQl3xyFsF6/BpO764nUZM6bZff8HGmI2G30WsoFLOW/uhs8uGWZ2dQrxm2im+CHNjjuNtZlJFxaEODKGja5//B67LUpJwFqcX2fwh4jbhCw1NNfBbP4buG7lRp/WbAJ9KaBr4jQ9TOLfdZB3aVKYPreDvPyCCllCRm1h6Hlf2JDyuFmzCc5e2i78wV+79tAtbZqwGOxwAXK5Oz1+MMAqmAUToYvXb2/koHkQPpvYr19NWeS1ddkY5Yy1c9zrGpAW3Db1J1pAdx2XzSfV93lB8bZte1vprEDwkdUOTbG1g5/CLQsIPcrGH8r2orYnTGaq+HgtSilYW3F2PeOlpA8luh/lh4hVBVDPwxQeJiJ949sHn5MFt2q2+yt6H3CKAq4y0OjbjICny4ginxHbJj7kkbFkF8Qq65+MZyEy7thvAQzK7Yfe/2XFpRggRhfn1dislHxoNwrJyOQ9xx4a/oCigKabRHXCPszOYHjSCAR8j65TwUqI/ejI2Zp/In7/437kE6TRR6WL4dyVMq4w7Fi6Iu/Nr8smOyGnNk20yEDI8G6+tS6/KueV+fEt9fgbURHigq2YqflhcVAE2b8qi0rM5QD8gKXaT2zJEAx8QA3hH87F9+HJUM
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-stack-postgres
