---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk
spec:
  encryptedData:
    postgres-password: AgCcoqt8SRo5aNBtSq9fCfVDNoDz4BPGkdRDmDEo6OWixJWmatjeeA6rkbPKfX2ErKu+mWctRMwQ2hE1yfM9MC6tNfcRiRhtMtLg7bE4xBfz/X1EnY3UxKZpQyDc0xS+UgUxl5tL7ICn87ZyiSm5MMn+rVVVrD0S+CuLqVnZPl9D2fzaYFDSNO/oIPn22Tt7TJexE+3SjDG/9mLEzsean8/MMSM42LYLTuGOnp05Wzhpqoy323HIy6TvowMDxSL12o0DcbBRJJcpkEX6q/YMWnGLWy3xPwM659BKsqpXeR66U8dY/U1nJg4t3Q/6ELQYKaZsr+WwKgkjr+/8N6+fCtwqqXQNezwMgCmvKZOdCOA4u6bCNDvEfVnC0413p1hIuU037+SJSG0ROYFvXnK84hYrzKNINNhKVDQxHKSEFVZfTJWenYQKfDaRFkMvh8pGay28ftyvK836c6KglPaPIj+vF1Bdn2lgDJjzeP4yuLM4VYGD3aNAmUkc6sq8SYTvACeRgMSAj0xQORNIusCRdQ60Kmghl5Vgx3OVshHCzQJDCJagcNDJdxEs/HYAZUVUJlsIHI2S9VyoPTs8wKAUU+jxnX+EWRL+JY6EWD5DCptdJQY6QJlWI8HHch2wGDhEi4Ay2YikqZf9wLvON5JvwuFvMO5nqbxOO65ih/QEwxagt5EE51pzi2puQRMXCHip9j7vETNCozKI5m2s
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk
