apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk
  project: infrastructure
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.12.10
    helm:
      parameters:
      - name: auth.database
        value: "tyk_analytics"
      - name: global.postgresql.auth.postgresPassword
        value: topsecretpassword
  syncPolicy:
    automated:
      prune: true