---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-postgres
spec:
  encryptedData:
    postgres-password: AgC2hJUklTCQ0lYdUY3TzBv2ldDJpTW3QvtCiId552VxbKjzfBCFhqq3XmeC9ekcedzj1TmHbN5tO/SBr1p3NUx+OfdIpq4REXl1aJikJNo68AoB2hYbNbm3z+pwEWvSJ9mRSZzT8fG+0xahvZugoU2NY5T91Too0zYyrGoxDtizOgnDPPc0tbNuKmspcWSz4PByIs59GSLgXtFEj14voQcAJ8ZBGJ8y7YEZHgmdv2uOttaWJRLVymLOAkAXYppEsxOFKI92IB9lHX5PwkE72ct9mnKL09Y8p3zfIBLklMLOFwOMfFmQn0GVAsuiUQmsXmFIeeBHYBur4uJdU0fAbKpMjtYc8vw3V+qQp4D5tvglw+jW2QLq+HKhxUdT8DK7JMtDWJNPlakDEGM6hFgFJ3DPK2rJ2vHVAIsukrtrs0EJ0cHqsr2T9sPXTVpZkMQHtCC2uZ2dlE14PAE9V7guFyo+tCYSqaEMz7xbQHLFvFMoHDuwY+t4bTs2EJ7qwtic8oRHrztEa3GKonInxX8crbGIQTlo67NA43ejdeyUPuIcClpfAJMCsawLKh5Iegkqf5jOpZMCw97mbWge1ShQqS48prVG3ebie4GX64x6jnYzRcvwUoF/XBxG7ALKIsHI8/jJ6/S0kwBaIFymhF72VTrJMvy8j+cvlit1dIXXMsQ35AaRYTqYGCC2vfgfA/wcSpY3ywn2wnx7c7DF
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-postgres
