apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-redis-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: redis-cluster
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: redis-cluster
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.0.0
    helm:
      parameters:
      - name: existingSecret
        value: redis-password-secret
      - name: existingSecretPasswordKey
        value: redis-password
  syncPolicy:
    automated: 
      prune: true
  ignoreDifferences:
  - kind: PersistentVolumeClaim
    group: v1