apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.0.0
    helm:
      parameters:
      - name: grafana.ingress.enabled
        value: "true"
      - name: grafana.ingress.ingressClassName
        value: nginx
      - name: grafana.ingress.hosts[0]
        value: k8s-grafana.org
      - name: prometheus.ingress.enabled
        value: "true"
      - name: prometheus.ingress.ingressClassName
        value: nginx
      - name: prometheus.ingress.hosts[0]
        value: k8s-prometheus.org
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated: 
      prune: false