---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgA722zegL8FJ6iMlFlInx9QuGasdgRQdkfo9CPf4chao0Hob80EuMzQBlXFXmJLQPq/40mai9EpB0imhUdQXrzdjfurWEe82K6h1wcKeoiN0dCDeSR0p03/c1a0tSal9YHhW41oQ6QzBzf8dwxcQNMJqBrjJ/dGrZBa4HSveot5CimEU+dNvVy6AtVx6Sdcq8izKbzILXE8MZp7gqHlUJFgAd+bXXDeH4ekiHcVJxY29ov3/xZ4QY0RZvwwB9JOThc88EOd5gqtme/0S3HF03o3bo9vuU2ImeFhTJkdf92HznM/pqQSmBMBPbcS9Wo+ce5Y1KCcZ06NNzT3jZ85lNwL7d8Zd19OaI2wumrfNwTlzy8u5b/9Cr72gAzkXChch7DvkVzanvcl3Wk++hrhJ3Dsn172U+9xI4QFrXV9m6J45c/dI2Lir7rW5drTfG3z3BjTGUI9FvWwZGRMtn4sJFew3YfZx+PZCLbNeixgiK4mKwQkbnsuvrD+5wPkzmYlXxrhnjhOjGdng7zJ+2lPzlsYg6bi/kil5rx5sZ6IARqWLkKVX+IwOaK0MAf7Xqj7AeAuYvb3zUKn3zHnzutwuOugN6J+GYKlJ5pjFjRmNc29nnVUgtEB6NBujTLQtYaRwIfSkVn/l+SoNCrkDtzuDCTovwnvsB8WAEJsU8P1iZuDiUqMqtWpEkTlUpBQBAk9xjJBMEdFoZPM8fngRhk=
  template:
    metadata:
      creationTimestamp: null
      name: redis-password-secret
      namespace: redis
    type: Opaque
