apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: tyk-postgres
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    # targetRevision: 13.2.24
    targetRevision: 14.3.1
    helm:
      parameters:
      - name: auth.database
        value: "tyk_analytics"
      - name: global.postgresql.auth.existingSecret
        value: postgres-password
      - name: global.postgresql.auth.secretKeys.adminPasswordKey
        value: postgres-password
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: true