apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk
  namespace: argocd
  argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: tyk
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: tyk-stack
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.0.0
    helm:
      parameters:
      - name: global.adminUser.useSecretName
        value: admin-secrets
      - name: global.secrets.useSecretName
        value: my-secrets
      - name: global.redis.addrs
        value: tyk-redis-master.tyk.svc:6379
      - name: global.redis.passSecret.name
        value: tyk-redis
      - name: global.redis.passSecret.keyName
        value: redis-password
      - name: global.postgres.connectionStringSecret.name
        value: postgres-secrets
      - name: global.postgres.connectionStringSecret.keyName
        value: postgresUrl
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: false