apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-infrastructures
  argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: infrastructures-apps
    repoURL: 'https://github.com/caroltyk/upgraded-parakeet.git'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
