apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-redis-tls-test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: redis-tls-test
    repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false