apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-stack-postgres-demo
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  project: infrastructure
  source:
    path: tyk-stack-postgres
    repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: tyk-postgres
  info:
    - name: 'Deploy Tyk Stack demo with PostgreSQL backend'
      value: 'https://tyk.io'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true