apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-oss-redis-cluster-demo
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: tyk-oss
    server: https://kubernetes.default.svc
  source:
    path: tyk-oss/overlays/redis-cluster
    repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: false