apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-stack-mongo-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    path: tyk-stack
    repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
    targetRevision: HEAD
    kustomize:
      commonLabels:
        tyk.io/argocd-demo: tyk-stack-mongo-demo
      patches:
        - target:
            kind: Application
          patch: |-
            - op: "add"
              path: "/spec/destination/namespace"
              value: "tyk-stack"
  destination:
    name: in-cluster
    namespace: tyk-stack
  info:
    - name: 'Deploy Tyk Stack demo with MongoDB backend'
      value: 'https://tyk.io'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true