apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-data-plane-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tyk-dp
    server: https://kubernetes.default.svc
  source:
    path: tyk-data-plane
    repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: false