resources:
- ../base/
- tyk-hybrid-sealedsecrets.yaml

patches:
  - target:
      kind: Application
      name: tyk-hybrid-dp
    patch: |-
      - op: "replace"
        path: "/spec/source/helm/valuesObject/global/remoteControlPlane/connectionString"
        value: "relevant-oven-adm.aws-euw2.cloud-ara.tyk.io:443"
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/ingress/hosts[0]/host"
        value: "tyk-jupiter-prod-dp.org"
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/ingress/tls[0]/hosts[0]"
        value: "tyk-jupiter-prod-dp.org"