resources:
- ../base/
- tyk-hybrid-sealedsecrets.yaml

patches:
  - target:
      kind: Application
      name: tyk-hybrid-dp
    patch: |-
      - op: "replace"
        path: "/spec/source/helm/valuesObject/global/remoteControlPlane/connectionString"
        value: "relevant-oven-adm.aws-euw2.cloud-ara.tyk.io:443"
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/ingress/hosts"
        value: 
          - host: "jupiter.org"
            paths:
              - path: /
                pathType: ImplementationSpecific
      - op: "replace"
        path: "/spec/source/helm/valuesObject/tyk-gateway/gateway/ingress/tls"
        value: 
          - secretName: letsencrypt-nginx
            hosts:
              - "jupiter.org"