apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: trust-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v0.9.2
  syncPolicy:
    automated: 
      prune: true