apiVersion: v1
kind: Pod
metadata:
  name: busybox-curl-jq
  namespace: default
spec:
  containers:
  - args:
    - sh
    image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
    name: busybox-curl-jq
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - name: self-signed-ca
      mountPath: "/etc/ssl/certs/trust-bundle.pem"
      subPath: trust-bundle.pem
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: self-signed-ca
    secret:
      secretName: my-bundle