# kubeseal -f tyk-secrets.yaml -w ../tyk-postgres/sealedsecret-tyk.yaml --format=yaml
# kubeseal -f tyk-secrets.yaml -w ../tyk-mongo/sealedsecret-tyk.yaml --format=yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
  namespace: tyk
type: Opaque
data:
  #foo
  APISecret: Zm9v
  #123123
  AdminSecret: MTIzMTIz
  DashLicense: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhiR3h2ZDJWa1gyNXZaR1Z6SWpvaVltVTJZVFV3TnprdE5qQXlNUzAwWW1FMUxUWXdPVGt0WWpZM09EQmlZV05sTVdReUxHSTRNekUyWWpCaUxXSTFNV1V0TkRSbU9DMDFPVGsxTFRGalpUWm1NV1UwTldZellTeG1OemN5T1dSallpMHpaalprTFRSbVptSXROelZqWlMwMU16Um1OREUzTm1VNU1EQXNOamhoWXpVM05EUXRaREUxWmkwME5EVXpMVGRoWkRrdE5qSmhOalF6TmpGaE5tVmpMR0k1TWpBM05UZ3pMV0kyTkdNdE5EY3hNQzAwTlRka0xXWmhPVEEwTW1aaE56RTVOaXd3WWpjM04yUmpaQzFoWmpCakxUUmxPREV0TlRJNE1DMDVNRFpoWWpaaU1EZGlORGNzTXpZd00yVmhOMkV0TkRaaFlTMDBZekZsTFRRME1EZ3RZak01WWpaaFpHVTJZVFkzTERBME1UTXpNVFpsTFRRME5EZ3RORE0zT1MwMllUYzBMVGt6TURKbFkyRmhOekUzWVN3d1pqRmlZV0ptT0MwME9HUTVMVFJpTnpndE5XUTNZUzAyT1RnM04yRm1NMk14WlRrc1ltRmtNakptT0RrdFpHVTFNeTAwWkdFeExUUTVNMlF0WldSbE9USXhZakV4WkRkbUlpd2laWGh3SWpveE56RTFORGN4T1RrNUxDSnBZWFFpT2pFM01USTROemMxTlRnc0ltOTNibVZ5SWpvaU5qRmpZMlUyTW1NeE1qRmpZVEV3TURBeE9HSmlNVGt3SWl3aWMyTnZjR1VpT2lKdGRXeDBhVjkwWldGdExISmlZV01zWjNKaGNHZ3NabVZrWlhKaGRHbHZiaUlzSW5ZaU9pSXlJbjAuS3R5aWp6eVd4alVOX1VkbDgyek43XzY1QmJXNk1SNDJVV2l1X1huSmVtQnc5MFFCZEl6T1FhZGhVOTlGNVdUT2E5RXQ4U19menhzdjZiXzNHZjNHak1RbkRxc1RZMnZja1JUeXpteEk3VFhoTVhhcHRoZlhMZXhBV1BsVzhJZWNXS1hNMnhUbVliNmQzeWpCNkRQYkg0TkFHVDVzR1lyUTE2dnFKVXZUM1FOZ1VQZEE3VWhnb1p3TXYzWmJob1hfTHF1RDJMcFR6djNXaGhYbjgyc2hQaUlKMjNGRXZQcnFJbVdqWVp1UE0tenNNd0UxeENkV0FxNzBKS18xQTJjdFQ0OTNWM1VXNExVQ2NUbjV2cTdLZmk2SFRycVFmb0FpN2pWY3FHZkkwR2lNeHhWcXhNNmd5bmt0bmRNeWNRa0Y5VENjZE93ZEo0aEJ6RDJhcUo0UjdRCg==
  MDCBLicense: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SlRTMVVpT2lKVWVXc3RUVVJEUWkxRlRsUWlMQ0psZUhBaU9qRTNNVFUwTnpFNU9Ua3NJbTkzYm1WeUlqb2lOakZqWTJVMk1tTXhNakZqWVRFd01EQXhPR0ppTVRrd0luMC5XQldrWUNVMnhLNkw3eXBGbWdzRDlRYzBvb0NCOHFxUTJBV0xDLVRRWnJyY1kzSTFpeVdrZUtESHN1NzNlazFqeW1tN2FtRzNfZWtZQkVuLWNSR184OGFIamhoVWZ6SXY2dThxMmZYU0t1YWJQRkUyaUE4d0JhcG41ZW43UzY3eFBqcTdLVFp5NzNyUHpxWTdkUVRld3YzX1Q4NjgxLTkweXl0ZUk2elZqNzJhOWRyenV5RkVnbERfQjlPX2oyWVlvcGpUeElQaU1POUNQODRRNGYyREsxd0xwdW1EVzZNLU1MOVp0S2paNmZRNHRBNFU1VC1kYTFINVhQSWNfeTRXRmZJQmplUEN4aVNBaExLNmtyR3AzUW5RT3h2dDE4Y3pZWXg2UHdNdnREeWlJYms5RGE1bjA5UE8wTnVoemZhWVl2Zkd6LVA0OXZmY1hNTkN3Y3h6SkEK
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secrets
  namespace: tyk
type: Opaque
data:
  # carol@tyk.io
  adminUserEmail: Y2Fyb2xAdHlrLmlv
  # carol
  adminUserFirstName: QWRtaW4=
  # cheung
  adminUserLastName: VXNlcg==
  # abc123123
  adminUserPassword: YWJjMTIzMTIz