# kubeseal -f tyk-postgres.yaml -w ../tyk-postgres/sealedsecret-tyk-postgres.yaml --format=yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: tyk
type: Opaque
data:
  #host=tyk-postgres-postgresql.tyk-postgres.svc port=5432 user=postgres password=chZrhEPfpB database=tyk_analytics sslmode=disable
  postgresUrl: aG9zdD10eWstcG9zdGdyZXMtcG9zdGdyZXNxbC50eWsuc3ZjIHBvcnQ9NTQzMiB1c2VyPXBvc3RncmVzIHBhc3N3b3JkPWNoWnJoRVBmcEIgZGF0YWJhc2U9dHlrX2FuYWx5dGljcyBzc2xtb2RlPWRpc2FibGU=
---
apiVersion: v1
data:
  # chZrhEPfpB
  postgres-password: Y2hacmhFUGZwQg==
kind: Secret
metadata:
  name: postgres-password
  namespace: tyk