---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-postgres
spec:
  encryptedData:
    postgres-password: AgCjE6wrSv2kqpGTczqlOA1IAFOOPtOJpZ++PXLyt74bE7yAzDN+FXPFVqfneJHrGsmoYbXLMBnU8nzELTAPupUeAqhfADo3xIgxa9ETAU9n7DZ3nnr2PNIQCQPytLzFWocfVYw+JPp23zEheZf6Xl82dq4VHyUqpdqT+65FRlZweZSM7T9xQ//NpB3OT6OgGuYtUTQGN6VvMa9Xmjm3ushHkZX9tLrzuZgbr5HV/EkIjrSLAHRneyIU/fno6j80nWNhsU2q5Qx3UjEzqxBcGjFSFnlW3ICx80W/KzmO3+gUVGEC8Snz+voXCKnUy2aSC9eikIpZ/yg5CZAjQ5Fktorpal+D/gOZC6n1M6TWQDxF4wHreOWtG7VFmwH/ZVD+cbHsVkXa2qMSe1M5IzEnPSmUBAyDD3u6Mxlgv1OJju4r1nxhoEU5HzazNRTBIbC+CdKv0lbgGiR+o5tovMR7n3NtEK8msAZ+v04X+lN5mPqYBfn8Qrzv8Tvvf5OWPUUfG12uG0Co6ewvSMPniH/ww/8a65/atdNNn9gp5XIooAJvJUct41VwzGJTcS+6ZUtqjLYwNmlGp/GqZeZ1QJWh0Mh1RDGzbhgKkWngeCoFJuQVPXxAMl8iSJc4RD8m6G8Vea7XMKi+syNu0eFf2r9w4ItkSq528O2WlCqPSsYoL9vfesuqQqPBp8I5CC4eQGiQvdje02nBgLUTlTUM
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-postgres
