---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-postgres
spec:
  encryptedData:
    postgres-password: AgCEivhqRFbkgGM2ebaRcMeewxVjCJpF4nbnW6CTV6SH7daTSqGHwuSktSVgCLehc1SMAN/ZVTN9N1mjRIb/VysjB+9P/T4xXNigLcLd14F2VICr5c4mQpu7whG7ObVldiSP63Z0LjkpcR5EPojHjI2EnopcgffWTaeMa4SrAjp45kuvdrFGnrhyWdwBIJwDOpui79jFDp/8q82b6CXAfcT33i4Si4dCAoyuzvUmEbXjSmVAo6uUVfnhQG0fc3nlJbJl44D2n6hrst6xc4vzO3Lh5ZuDcjC0z4Gb822Yny7ZTi+52sWnPSrHIgDPe63akWEOCCHKQjKFH6ZZ+LbfDmZS3JYKV9f0E8y5nU5+1oWy/s0QnibTFfULjYBoi0hlV/VDCVe8yhXRdCW1/jEjof3WM2cpjfGFj+DpeD2pEC9pLz8xV7Qhz65NYIcNJfq7PcQgFbSkZVySftpph+RAXLJogHLhZurlidt3UWhlJH/oRIsVN+VagkB4ME6ihnx64/Nl68QhvRVt7h4S8ZQmxVM1hqvN0qfLb2xi4sr0PXAHIfksoQmpID0FL1m3fMMYb0d+q4zxUkGafPE4t/a6Aytrrs0/QaHf/Ot3bjCU3tEcc+NpyD5dWBmqZRHuu6wN8fwZFw21r7vqVA0PL7t9gcmYi7oGiPEDO4/s+9m+KOPDmyxEhLyTWbaEkVN3URYXcc6i1gcKHuGOw7X4
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-postgres
