apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-oss
spec:
  source:
    helm:
      valuesObject:
        global:
          redis:
            addrs:
              - redis-cluster.redis-cluster.svc:6379
            # pass: ""
            passSecret:
              name: "redis-password-secret"
              keyName: "redis-password"
            useSSL: "true"
            sslInsecureSkipVerify: "false"
            sslCAFile: "/etc/ssl/certs/ca.crt"
            certificatesMountPath: "/etc/ssl/certs"
            tlsMinVersion: "1.2"
            tlsMaxVersion: "1.3"
            secretName: "my-bundle"
            volumeName: "ca-cert"
            enableCluster: "true"
            # enableSentinel: false
            # sentinelPass: ""
            # masterName: ""