apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-hybrid-dp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-hybrid
  project: infrastructure
  source:
    chart: tyk-data-plane
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.4.0
    helm:
      valuesObject:
        ## redis in tyk-hybrid namespace
        global:
          secrets:
            useSecretName: my-secrets
          remoteControlPlane:
            useSecretName: mdcb-connection-secret
            connectionString: ""
            useSSL: true
            sslInsecureSkipVerify: true
          redis:
            addrs:
              - redis-hybrid-dp-master:6379
            passSecret:
              name: "redis-password-secret"
              keyName: "redis-password"
          mdcbSynchronizer:
            enabled: true
        tyk-gateway:
          gateway:
            opentelemetry:
              enabled: "true"
              endpoint: "opentelemetry-collector.monitoring.svc:4317"
            ingress:
              enabled: "true"
              className: "nginx"
              annotations:
                cert-manager.io/issuer: letsencrypt-nginx
              hosts:
                - host: "tyk-hybrid-dp.org"
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
              tls:
                - secretName: letsencrypt-nginx
                  hosts:
                    - "tyk-hybrid-dp.org"
        tyk-pump:
          pump:
            # hybridPump:
            #  enableAggregateAnalytics: false
            prometheusPump:
              prometheusOperator:
                enabled: true
                podMonitorSelector:
                  release: prometheus-stack
  syncPolicy:
    automated:
      prune: true