---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secrets
  namespace: tyk-staging-hybrid
spec:
  encryptedData:
    APISecret: AgCCYZfbAcEHjsbdvd0Mmo/FnAy/fGRRlWHuXzC3fjp/WN4JOqErXv4iywdAZto3ylzmhVp0F9eMy5tqNJLzG28v10pyA3amYgr2m+XKYs06Oy0hSYz1h5nVYxOQWXpLnYHEeE55/0Yx0qXvnJldNKGhZvUbgNgu0OJyWo0JEeJujZ57+BGUe+3dD9fyj40InenW4O6UuNvx7tz7b2zPvA0SOJt7Yo6zD7v87YOrfzjxwjzjXfeaQ+xvtKly7a+hWukYrxCPi6v9GGUf114SDJ3ilTn4u+ToQE0JMYDjg7+ot2ytSEPDsvu/WdGShHVxwoKuT+RrC7IA9LA0Q9V2tm947iLGl6ueWR6dl6AX4JxSNN4YX/Yv56hHmyLD4bWfEdk1IgAO6WetrEmiYMA2UCzoBlULEY8djMb4d2V48BimQRNnGYgNwctnXcQLAgYCi4gFD0GVcJ/9ZUrEUB4tqUMseFQq9JFKqxLEn0aoAaqBxIDucIz0SIu5gqJNsAAjav95990dJP7mx02AWyXF6/WqaG1iyqSHtJidq/TGMc0ih3Bwqi1mezOzW7QgleLHUCjHwPJcO3AgMauqTJyODmiLZhcPeanS/v7SYPoJBzMUNvJGUf7w/aqjlqnziG8I9P5NGGxivTX8xai89rSXXSYzHhMRAAptPld6ihN/O2pUCJ0gZihHGa02UG66mMMkha0h3Yw=
    AdminSecret: AgA5qgZodfOn8RpdHRsO8gyxiDsGz3mNOeLgcUlBvTjrWSobAowWP94hi2DBOs9GN5vNnjC7FdGtaXYtns3UBzQiuMznVYYfqCriuFx1zcf03MvIZn6EM9wIhu0AkloVvM51dF7RwAWAaroDDa+udOcdYCEdHtMnSfh+rZKBk5wv/URfz2mC8xGhvE/AyzLeemg/nB6QTmf7rIzDMjT52vlmwEZ9OGZIj5DioP/MnZo412WS4CaJVvB5jBU3HYBD9jCMytwsKzp5ilnCC9cKLTHZYsPTrQtco0cBekXiGeJCqiFaR+lkdiqnAknGJ4EZxdsztbv+4cogJM7N46DNPkXjB/9b5TPDjujiil6qBw1rLZTN67S77LT/85BxvTOqspLHp5e3R7GIsRV6zVuwxon/Lyh5xSUc0beUCU74j8b2ZSJQf/wOj9W6DmMXhAuwGLMZpidEiCDphMnA+PWc0lSo8l6o8jaVkYGsH+/Pthr1smn4jRVOrPX/vKqB9WUXXqrHa3Kq/AfRUJ3oTfxTe0IQIh866AX8/cEoMTx9cCevob8J9BX7peDgRc32w6ci4NeLyPqvsYnHDOUof/smOtmsKCbuEC5BlDqybM+AZLBrnyiR29PAnb848+6l1vI0N8sEj/qPxrMkG8Pr+0RB+SMs6hBUa8Tv5NGSVI1eWz0eVp4B5gPk10RbWD1t0PY22iQOtykYbio=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: my-secrets
      namespace: tyk-staging-hybrid
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: tyk-staging-hybrid
spec:
  encryptedData:
    redis-password: AgByTzZ26Lw5F4R+2YJixfk5QaV24ICIXtDjjTMXa5UF50f3uU7OREURXqOtaZbW4aL1ID84fQzh46ykedDnjDGC2yJZTEukxfDG0y3jjM4EQsHCfF35RX9QCftRKRKlGSYsoVGYfd2D+olgoBScP5kduaChWzyLz7lLQfT33UGatcYxj7KLSFMjSbM872NNuJrzSvUrobUquPuK2LzALuB1oQX89rqJtOCpKwemGZR4nBLgNk0/xokUji249Gf9uGugxVsUFyoVpEfqSuAW7R912cXaBiReK3zm8zDOT76fXhxFFMWNTssgrFgGn9nFBg1aotjL+FFpxn0TVvkgrrH0qk9tTUx/JloUTgHJrr6daH10/ttJwxUkEFbHXKbQSnS6sgn4nZwMik8cLhDNqWmnIw6RJXf/N3A9d6k6utcR5LOsMlqDAykfkzaN8knmeHiv+wLbjD/KrOv+ozh1I6pYKpjAVxgqB8YLkwP21XwKnsS5huK6HBXczQ4D4blOKL/sK6giL3iDNQhmM3AqPnfAqhROngFGwBX8qrIQDWgQ5ymrmhzEgp155TyMlEB2BdYbIcZjCiSbDMt75kaSJ9RRe67TgTX75wr0YXYhKn2aKyNS5LI3ir3K36RTo56eomdIqYaiibyGRq8yDgyvB0Y7huvZrnr3gbDG+PztD1CHw5P78EALJJrBxatZgZHSM/UjM7HR+9jpryPrvZ4=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: redis-password-secret
      namespace: tyk-staging-hybrid
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mdcb-connection-secret
  namespace: tyk-staging-hybrid
spec:
  encryptedData:
    groupID: AgCBWJf/EgcNtKYCqMvj/8SenfKd02frqbp08b/4pceTuwK1pzd4OouAkpSAuUFBdKQFlcndFutTgCBA60SIodl1t1NgEpuwTeL8KhhIXkpR4wXF/bbiY3UW+aOZd3TIyMNJpdZLntCT98I8w1IEPNvmgEPz2JG5vbrVRfrD0ZJUDgD+HN6DX1ZVbIjPOIOMD0nt3l6PO0rY4y+l+erlK8YVpyEoUlPgufOKWEhDov3cOLx8DtnhJmZma5sME48XLlGF4NQbIwUZ4Anz896Ufe/hvfo5rFtW1d7nPY3aWonI06k4tqsF5ecTJcmRKZHXI8NmZNlTdsOMghQ39jYY2kmyboTNNknYy4DtZwyib1Oe3vpEVu+0c9SN24pzKwMsmaBXuLtvZH+tzNAKcLeR/b65BaQ3L9i0FNglcFCalfozfQbkAdYz4IbtikaEGE/7AS8+Q1TV44sGV3ScJWcWQ+dOziOPW5u3KHd7pDmSlb6IXzEtdFE8QBA2Yq0oHoGBhZu3JY/pme11hd2s6rXgyM6v8c4qJcIVcIpf8QzO+z6qpNdiJTIF6FjcQuDC+BIRuX+5AIQa7K71fOS7DG7HxXwVMStorvwdBokzkyatBB6m9uQKLXAMKc0WA4LEKdq205GevyosLpCFSOV4btJQxwpBtNG1ExaaD9JDUm3DCu/wXv7X+J2jEmHoBeyoAJ2ndEgufm784A==
    orgId: AgBKN3Z2z+5GzWoU2yFBqTAdWgZ2Xt2+DnBPRyDegqqd8q0WWY/3wCERRe4UOqAgpErsFrD6B6xA85rCl4VEYQnyFPmq5G6hqcx6qhtWTZWeYf8LAEPhcoHaved27+/psQq1/t1GrSo10EJP/v5cO8HqhA0C9l2OPbMnna7HN291hZ12GaCX0niJobW/UuRSfzInXQTSQ/x2VP4rKfPoK2GUoaoPFlv5lAD0cUObf+/o0rGpWJs2FUU9k8VgeZ2ePKlbHVYDz73JoTvIFwNMwfCGfSYaHRMasri1rS1mvhYJw9ViWB/kJ4FWMWS38/55e0Gave791pj/Zjiqj/pg996xgRpJuD+rdgANnBJy3nV+i/3GHGNRPUqEKoMi61v003BmWANQQfUN3RHcahJxvsGeWN0ZBzgcDWQXR83h1jTq3mXPYWiJLbtx4SIoXJ5RuIknJkz8GmCho55rv8Dsh+dr7bJ7lCcR85H3jLztE7NuqION2uQgJ4VoXy/alExqvYjCTNKXXYEO7cPNbCX9Q14kImdTQrv6H7v8JHGBlnpZLxJFKwO6f/cJ33715AHGD16z8epE4t7y/Q+GLH0XukIpsaR96d1EWYlXt0rSF7aWELSITmUeWGJCFsZKcGUNBnlCeE3mjvWsoBmtC9LSL28fyKfRwkiR/GTCZ4wrwHTAOXlRUo4RwCKvasTTTK4IX675LAimiIn6y/otY1siQo5y3YR/HM24sLE=
    userApiKey: AgBmfhAyBBBX/34wTqheBhyoBzBgudTDITLMQyQ21d0R4tF3ltyBOzHl9/v+5kGyF3iqyYnXHE4g2GoF2coSUo18VZvZJZAouZYc/zZys9QSqt39sRz7e6WLk2o/IquxRIRKYPtj02ZZyx8lOvhZLL+bD/hdQQRcsOnNYVsADe4uZBeE5npLE/rDhpWXXzHPq/8uM7qy2GqSizQxhWtwomw58RWxn7WXKOgaFm5FNnG2Wgaq0JEacxaPi62nUcjLMvphTjknmlL2IclhjPgQ2Ex32CMpVdvrGAbPC9TPXsPnUSisGa9o5L/s/oOuN05yUFca0r/FVnClvbmBdGx9y0B/yGORsruhKEIs1e/ZKcNGVhjkXmDKY3NX41jeY2sUHesKEUn4B6sgRHOB8bma9Up8iTcOLR6B5vbXwzp7Syrd1wFxyQkWNdGzgdUMBKoeJAeZeKZYI/GmTgysExIVPOHYtqC2DsRtiS2fRPvMuSlmggzPM8JDcqdO7rEIuhj/svpqvrhSjfWIQzWoBE9luFISdZ8AeFlNe2PxYh4DmJEMXdwKoSi9QZl3XTjd+InwrYnmQicoF3EHQtojcVZxIQOrHo+/gJjVGLGkGvOCZkvtwNAPJGQ1P08IKJ+gzKDjgv8BMMAoqp1NpaRyQYIstVU240DJ/RRSFArQkcwq9icVyNmCaNlwD2MnDhlh8ChlMuNJnEb7JO5WGntIFvReXcQS/M2o6sAdclr3hg0yUKdIsw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: mdcb-connection-secret
      namespace: tyk-staging-hybrid
    type: Opaque
