---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secrets
  namespace: tyk-stack
spec:
  encryptedData:
    APISecret: AgBzTtNoqLKAxF60hWYsU4xp+tL77JbC9rlxyM1G0izR1XqFJbsBL+e7iXAOFFF7ml4zaGQAgYFJpFs+BJnEs45ZQD35/oDsUidmcUc8q7hpTfM/N1L8XHtimu8edxSqvo8Wkk8QQ+V7IRNVvFv9jY8s8MPuK5IncofF7RcW7Tqg/HKRTo9cm5etyIwj13TToTaR76paepGfP+wdZkN+ybLdnliwQaf05l2kq1URIuQYJZgCTMkTbxEoehKFxmLRoEwM+hkmDLqUz5fEApE0nhOlkaSfOEPcehwViLZFpWVfoSo4a24RS6ToEW5tZn64zui6v9/PMfo2WZC1GcLS5KksCdnYMchcdVCtZ4GXQpopD7yoofCRHyuXiaNgBLy2iABppDgf7HDxzMz9EzCiJf3WsNnQhoXlkikPSHBevf142wWbIkgnxflujL3+1TtAyG/OvBp3xkVoRZ32fF+dDkXYWg4//KhLOHgGqNIUxMYon2Q+D0IwaDifdKNFH71WW73vJUkHxriCd8Ajd5UfC4JCMSwOx55X3rdj6Z9NPVrVkvzoHW+W6hlgGHm2jd4MftrEEv6XGdTu+GFvy7eOaXatmIhihwziOY1j6WFdU0HWi4E2841XgMi0KAFQkdn8ejmJxwAN0TY3xrRbT7Bb6FNpZJNejggBiX1JsV8JEYlcASpRouocHZOo013znRhpi6ACsNM=
    AdminSecret: AgBTwKOwWCu7qyaINUiCDbexMPeR2cuSuDyIWQxRypLm6Ym2xGIE0liQiSpRuA44zb2bU3fx6B0m6Y9JJv77O1MsDoyL0/owJNJ/q4mxyPmKDWWieLH4T/vhiFhQpKm1DHzR6ss5odQKbpXwSl/SujOCqo9+S8JXVrgLBdBPVsf6YO26Fy8H1/3zQJ3k4oGJFJK87XDsnu14Lx19DNljBOP5m1JVJwb0zb0sCh/cnMCH1JhnIrw61P+oGdPOkR+Cf1/PMX4IM0y1U0SkL/ukFvGCTWIKOhHsGxcsME0ujy+4Ytu5nCkl98CyozTpnqUfuWK2u6bdE08q5TkPhEMs3l31Ucg+Sl4sxQfe/xVR4YQ3ImyhNobQrKaSD8Qn61wa1uaC5oWLwDT9AJ/yma1D+XAO0U6oGLwz1RQxPkPn/sjwiRhxoa+KOjlej9GKc2dcZCko91qmvAPZgZhnb6+DOG+bGWhAqE1B/U9Rch3gd4AMXHqElXa2aQT/TqPPTiNuEGn+OPkI88e1CK4w3s7U61YDN+t3fkh6ZqSU/lraW75/xBGcqEmymhRx72zc95H84vSYZ6B0PO9XRCpUVu97x+Jx/l5BcFjGtRRyy6x6zJDpg+vn7izZvtWLGBKJ3eiKyi3xLvqpiYMdtjbnMCplo0050VAewi2ixiyeeo4cA/Xkn60tdtl9mmopU/ujhjdQsmJSXhP0WXA=
    DashLicense: AgBSPQr5zEil+6oNjei7TKGl6uiSPksg8dLXLc7KmWjiDddNHMHTFfCps82HYSafKcfd4GX1bjAg1aSnhbslEvRWD4Fu9tqFVW/6y69zUuTjo4AGIbkDC4VVp5fCK+TI5KEy6CiBxIRCv65IU4urKdyC7YVhAq60DDb0u+E1PWleFtjT+H9LWc9OZhLPv4tY9Z62DBKvyVtpskgsW97Axrw676lE8zvOZULPoxfmNT8axLZ+KWnjwAfY57myUTx5ElUzEMUch9hW+Ypn5N+o2iaT8bpVqvZJkjVWbZbTBvOpBfria9ne3HqAuH70DBwAxA/qeIiNccyrj4fM6U385XKbHrAmJja/zmd7z80bdWf9oS0OHxIolNVfI9crrk+RfG+q88F3Uop+Zc38F7EBExAWBhgJ2b1cIMe8LHwnf8FV4Rd4ElGT3l4BKRxX2UDxljeen5HqVT7zb7tpVifnKnVQUG0I1IHU+SYPW0U/pDapDS6PGBaDQzLE8E/bn/QbiS6pS411BU5Yc3ZQjDCW9CsdUdfhLwv4VdHey5w0XXDmS7xjuAVhCEtVo5yUA46XMc3lXia3LszjvAGzBQcFtI4xuJ3ZUvJOVpujPNAy4SgLsp5d8utyqhVjIpYFYQbF013ue8LOZI2wls6X+hMa/+4KvCJgdjAQYigrS2Sqsl3d3bOkmULVREXdSeh0YSJi6oBL1h6nfsLL6lnmVHcJo2wPqRRMO8tHWDXFXoUZBoXqDEntv8uTbJsxL+ooUVi33199VzZfuBxIGcdeHHjDrf+5Jo56AodpQnU8U44B/ml73JMXuEfo5DePTlfg4dJ6KHgjeKWhUTVHA9CdKw9v9zXDAJkFm03UsfXn435OgqGpyGOFC5FFepgjZ+24Cf81PPmT2UOB7aELblf1aF1ON1Shwr/0f0sOttMP3jZadeRNwgxUxizwVcDq6lc1ueVY9ixKp/G901hQbdtWTS6OpcC5gM6CS7+2WwAkz0Zsb/DOkGhIhTTl+xFE2kQ2POZ5IJsevrxSSE9bRW6/fAIhbbpzDq8zex0Xa8VJgKCzFp17nzH4in7SMs4nfT4f1PQCZ0gpQHM8Pxba6i/RKLZl76oDXO2rSngXFvrkUKPLlZuggJSjIO/scTWQZcAtRa8+62HH5Jw+wCB/TDGDUzWZpjGDDWFdnQbgeI1gfGr03qXz2+kBcmabaWoEquNPvRw0J8vERMKkuaYBwIQWPllK4haq67XVYjrjcQNnGLJI9uXmoS93wjlFmifzmcjteuPuqvw/sqxL+sxlRU1qJQ2xyAD218jD2nffw5pEGJhpo29CMSRnCnA8m1hiQHt47xOMlkGUIDmEcqOArs0rx5Edj7OihMuZRIxNsIKyb5oShS9HMJ0B5KFg7MF2EnoLLmZJsBz5xQsQdvfKfI26keJQoGlKjAGPnqiXvSzNsukokVjTaVrlPySMpIg//17kQldJlqHJzQQltoy6gtV3WunRWY7c/pwAWMHbRwq04P8XfxiXYbHM5bvloXDNQ2VkE/CaQrxU9Fbllh/Ia0UeC8JrhAz5w9stvvGefqp3jT70sQ5ghaltF/NRK5PlXhfq6QV8i3Z6NGOASe9oQaI+VSvCql7U1ntXIWHUj5IrJV88cP7bGlBhp5WCKCaldtSUT3jCOFUq3s7c28Bp/6mBqXXpqOemvwA3InoBdGCfDw1pIAe3lavPbUoyVxfIejQgvMSarZZRnJlyDhEPb4fbgduMWSc4veTQSfgkNIfVjHXddqTmT5u6JveK32Lrjpx80mXIrWnaPktn/HO9umGG9gjvWAylrkNuQ21KPvf4GHl/9Xs+syFC068o/TBfzyKUPpfKA7kkrrQdiI9vT5DENquvWyYOUxYnNqCoDFx6Xl2DPsP0tJU9xmJYM35ShgvgxeMgeRI2OuX3TquL1AHA6YkY8Va6AJKcSd28bXZ+4113YZ165o/Fx8kCcQAo/mpjO5AOKaUtm38VCGb0nsc3muI7xi2nyCI0ls6FuVo4QGj3I833gFZLofahYEEj0MIFOqBRPm0cOX0evCPyNyE3X/QBcysMV78f4wpjtkj6+v8CYiuMy5vjA9egK3GXBtAOhTCCqldKpeFZ
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: my-secrets
      namespace: tyk-stack
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-secrets
  namespace: tyk-stack
spec:
  encryptedData:
    adminUserEmail: AgBJtrVoddlH/ythzWHjD1w9bf4FnrQX7mKw8tTxa2lKcprj8JIPTmKbnQVH+GVOqHmbPTdiFK+/GH/x1lNiIncfKgMx5yWpbbOvQJCNTCN0PGqrkIyvnorUPICfD5TcFIv/eFO0K7B9XdSZQxZ0Cub3a+i2BzvvmMG7j7B4fSqBMVVHtAE8V6NrBgALq54hh48y01tn5Nzp9hCEyCFJL6wjn2T/0WE6MlNXDDDBqZN58vxZnmACIxGkqIaUOF8X3cm4YRjpZxqVEx76p0MzCUr8ry5KTeXRAB/UAkkN/aPGZ/lWZu/t7MRa8o7xyZW0s++wpkbScJN2ijpe/OtAuqSlqvPhKfQ3r4AiTG+Cs2CjZGDYHuq6EizyjWsyQbtWYed6suO3R8HCudSLNN5GY7jn/XOr4Xo9mdLfgMex0iSrdHNKdQwGkLlYmHUOqZUBEL/+HNEYkp8jaeMRdsOk+xxgelRxb5cwJ1gfMregGwd1LbKSjBq4P1Uwln32HvFulk2IrYecJxQxdo7YfCtBywE5bwEzSGD68OyNCCLK9UFpD1JUGBZaWxexzm3c+zquIv54Vtk5Tz5qKEP5NEEe5T6ykDBOSfUgS4GFU5JAc9HBqu0VE+xcnSoni7NJ9BIlyju1bBRRvagdOWdKoRCSe81OOqMJSfbhJnajMc6ZrjI0tHxCU5XTIzXoJGNDSzIeONvcbBaiDoLRm/sRTGQ=
    adminUserFirstName: AgA9SZNWpWKzYqBsAtx0jjyx/57JkrZJ1dtA260nvtS0n17qNjvTffIGFpAeXJC9ECdkGns6r7Hg+UZXHiuQoPhj3sOi1D+kVIYONQS3vABSVGJLHdfBBPsIcx8GmKc0pxraEqBxWV9ZajgukcdehpmVk7109bnZIDKcHCKm9Z6MWS8ilmN/5sYkra/cB8G55BUMH/pstgbJCxpKlkSqGEez2eT/UB253u0biQT9e46MtEoT4kjSJpP3RayTCUwND80wX7LXpZJHdRsJ7uS+gO3Ghism9vnJa68N2OjOycsDpnLeli1g8cgbUEaHgQbGqX5KT25ju+oICiapR9BHDNuk/kheIXrFuAADPAAGlzfT04DaNAxxliwV6jeYEK1mNLneVVUuElImpQNHZnthrDAqaeajkf0EFlRh4dswivsQPZwmUlSBVhHVhfyZ5sj/81WKPB7nbbsPxDm7yMpojeIqyDh0KNtYN908sO/WuMUFJyirEuAEi4ogccUH5mfcHF/iguP63xLliUQSEqEpxsOZQBI0r+6wxMe0FcUe/nGfNOgPicLMKV+eSWOp8mDSmm+p4ahZ1k6BblcW+y5nar5lEF1WfhbV+0xCKSkmD0PITp4y/h3khlOi4bgDaz0reJUgTDb+feOhOENgx4HGi7TcOO+IV3/PaH//IuPsrosq/oDV565RneSTtiLXRxewz1gxxnJPpQ==
    adminUserLastName: AgAGRDkpJ8+zipZryU2FoIVG6i8bOtKA0NPmyvS6BdqqSgK7AYqC3ikKm9957t126BaJyd34uKXE/QLI5JSRGoGJb9pvIW5HMdjvn8blU4qNgea40qoeI6tkaxDNnflbCeJNUwQdoDTt1kci05B+YineOcWReX/FkcWEFioPZ/3w7DQjdRVkZTabO6HettbUAeMyZ69WsfWQiMuABkl0iSh2T1Or7LTbQe8ja0M+cCPkKON1xqVdx6FhCXZAsoVWnB91pVrgDFyqbVYfKMTBWQDOGDA2mf0h8BgPE3AvC8z1cYWkrBfIXgPxiiv42fXpgz17LUqy4ayQYKP+/fACCf96YU/9BbSMsFufgaMRqun5f2dfG54sT2QOjzR3StGhaO985NMHC6PsVvbttlX2h+RBxJFPLkiy00mMRkFHH2u7USUqZESdzqkM/IFk+2iPAw5I/KMJqYMWeFh1ML0xA595lOY2CmCQA5g5uZw6RprNvjcTlCwUZoL1DTPSL8j4hbi4k/c33wbOQTlCrEIbqgrVZrgfvHE+zLKvru4GfAQk1lr1/K53wv7aXYrVK3zo3v/9JBChNtdw5EAP7SpGt/7g/q6aGfMoATMk3K5hXgKVuVmbMb39PFRgURW2xuFnypefhc0zksjsB4qMI1sB7zHczLt0W5KsGbtLFjprQSaOuP+s0mgMIG4OhvzWkLCghlVntbYa
    adminUserPassword: AgBiI+TmhMtGVwBRzUYc4nwxNAzAh41ogA9HwFtz/hDl5M2tsSfNZw01EIoki6gjcDpSbIYM5v4/4ZSu38Y5XeJzWJS95ZCRhYEnu/WaOLmw62G/XXRXZSGUPt9pgL+0EXqfvjnKqPetrIQzBbcj++29w8+DayJtx+B+4VFaY6ilwE62/BXdCscDUJ4G7NQMmvJAepm44KNtlhuflCgv0ib2pbQZuZ6JQgk7R+uEoLtPm1MkyDU4xVW1r3ay1SrBmVy15D2DdJPIyI2XGJ+ND5b7dV1rtUNx+ZLFrqk+u5YonPxjfdW7SX/y7X0TXqSoZdK8dQkO36tJLzzbH4CUN0Jlgf0FCwPPtOU92F/B5lxQZlSF5ufEPyjkRTPVLwXMSmhnXqGUDvN9qruHoBhsCJ4xnZWGKjVWFlBmuYEJztWG6bw2PKiesr3Y9XtF90LPnB4CQWFtNCIs3Z3LlWqfXeYgpWe6OdZoi20aGrW1C+Ac+CyqR7jrX7W8sKAO8nF1n1edu7ciUldcWtMBUpUeOqA3kASWfV8chAinkeVD9kxRuUEt5t5GVIx1uRvJeG+eCxJCheCXj1wg15/3f7Y2A3csDqm3fkReodvwo0kuVhdThm3QXd6JOnTzR6Ln3Kr7/j1ctLelSz5A10dyatrUXGjKhjJALj26ndfjuIh4UxDL8OEUjTpUXw7kbtvXLRqQ7/Q4k9EGbDzD0HE=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: admin-secrets
      namespace: tyk-stack
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: tyk-stack
spec:
  encryptedData:
    redis-password: AgBqN/mVv3TUMY1eVOmZG8GZvLjy7ZtHHMQoQQFBe09E4t8QNmXYWaJsqpPT4zAF4FHPLsidF6k6cSCiNOfkICRPF95MdklDjgsABN7nxEaxQAea9vBShVOSRzVoMKL4egGkNQuVmrW6KoRsIxfEL/JgpJIkgkVZ4/6HFyq6NeWUxBirIkhjQzmDL3VKF4zUOUcazqzXvTc2oBCq/WMEQBD6AaY418JBSO9t+FDt1jczTEa3EmXiqqqafU+GtEjUZ9O3q7D0jcT5C4UXmGemHmxDpSxFELtr/G6PkEfyOdSFfu5XeGvilB1TCWi4WogOZ0x0URKDvuIFSDMw4hhUsBj5do1wv4dAScx9lnBXPhLs4Db9sEhs6cNMI5NMJ+e6h9PsnZZTbwX9iKCM5bQDxxH9/RBjojMAOAqgVLqulNhdoQAlnbjyPMZmIeKqn4NiC+G7DjM3GpNq0oC8ktXjP3z963TmZytjdQqXtl1eR131FQzwjyccqSINlr6kTeCFdmHkymmklH0gf+uOzp9KcALjqvtnP2B01SZjRX6i+1anoV7E5cjKH8hAk3y4SLNpB3lmsVql0XoMhWLfkSSrhrxqygADZw2ku70hb1SEHaZMx/yl5tLRebI/HBH2AUz9uVQzsSyhNNomNKtdsAi000V/3LvuAfHtE5KcELtgWDPOHR4dggBq3Qa8CnuH5VAVgRTiUruM+9MQerVbbik=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: redis-password-secret
      namespace: tyk-stack
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: tyk-stack
spec:
  encryptedData:
    postgresUrl: AgCQHR/DfMyzWu0kEovs2L5ZGucb1a8oFXiTkS9tD+nvwcO97IoN0CiSX9Ksjf4mUjPHmdgQMwB3DBDSABsTrwi/eqA1xGv5ScYoCsMzXAD5FgLWfOydgPJsSKKSWdas137uNa4IZdAI5AWYgzXH8bFa+k3muWQJMns4cV6ihCyxdtCFFY8Y/uc8GOL9ZCmIMtM4LMGlapPztJ7FqALkwrV7UrpngkrkLNhuH82pvuYxOm8PsJ55r2l6M9beiDT6ZUqaMmn3dgwlszY9LNTJGrE3FTfqaGeHT2l2P9Y1Ik7WONizFl+sc2Tt6w3KdV7zbmTbZGf93qs+R4/u3nVaYVlJrXI40EQHszvNSHIYaKTjfoYLYbtDgymQPZ9VA976W5C3Of+VPRs0EZqseIvkNmD+9NW6h+P1mDb0CUbNuyvo+DSX/ucONnTwPvJ0BCMoF8EhSYuV2o0iAxVO+99TX/l4ReneNbYrp5csGp1Oj3VdlEEdq/Mz2/KJeF+wAofknbrBpeAUOLEBqeJc4uwXJM2QkNhBfuFage6w3mwwqlOrNKLRIQSMhpdEkrdvy9nyRlh86jZ6HHPOr5Ss0o+8svxJey4D3Blb4Q1CmGhqu2ncqKSP4FB7Uq+/lran3UeEKdeC4GtqSdR6QJ61JBWpGLH1ECnoapBqZTfMKNgL8vxMa3xLRVLxXsrsEBlBvc5i0bhEFbwKRDSFfC4crgUpHYnXu/z/UlcMqVOw0SCy6VRehcvUT0cY6CojaupcDeZUSmhC3xrYhe6Yd08LUvSAnKj86wOuwPCWw3g0MMfrA0pjNy3zobSy7c+Dt3P1JooJ+6+UDNBVCFF62u8vDFVqsUTRsmAN+dZaMMJL
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-secrets
      namespace: tyk-stack
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongourl-secrets
  namespace: tyk-stack
spec:
  encryptedData:
    mongoUrl: AgArBz3nVgQ3sxxzL31L1u8GCKBczfwVK1d5VUzAPoZ/P7qVlWiw8F+By74bfwJj4ALgwgchbSwHvvuRJ+Sah5uRVPYVlOTkF1svtNdihW3yG1xP8sq+lGzUPCSjAqcDq/6qdzWvlybQzGgKEo7FxwsDZC6bdBF32N93yDdDYDej549JtIcLoXifMkPxHmG23bnHcwhUf474dsmsuL6nRoxkMxYb5yV1Cf2rTA/WgtY+5Lug5AxhyhaEGu75OpICC8qwtVKujBHYzAR2OjYSWeLCq6yjDwEbUBxkssCqDQMNrc7h+9eRUqMMXAtaMnwf5Ux04Xlw/EmLKtWWA+xMsW2tXd2JW5s0THWra8EJzBZGG1tKlzczmHRHNlMCJ1irgg4vBnQTS6IND/IiVvVD/vT3PZ9H8moado/9V8pncM/6qITvShoBKCzAZAKMx8rGx9rUjp+0CYzbID9OcIod7tiKSzSEnGb6tPEHFQGjU7UKDH0UBhJzD3raeDlnn/JEucSun56Xsq/7AKlbJB9WIm8JgvG7Uj+hXBPdIU6MD1dYvs2MqETO4FRYbyzWpO+B1UB1PlpfYc7D+Y0y99YD68YcNUjVf68mODUoccyO3ZCXSt/9gFql9T5nAfbwpaacQ/Bp9an7/alokPOx40za+gRWedVfy/L+SOQndaaE6pkcf+F6EKQJoprlWSEWbslxtL5Rrw9VnR1mwAM2uMEGtjLS5nemh8a4yCSAWac8Zs5SH3n1heh/Asvp2uCKy2vg
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: mongourl-secrets
      namespace: tyk-stack
