apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-stack-mongo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.1.3
  syncPolicy:
    automated: 
      prune: true