apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-issuer.yaml
- redis-application.yaml
- sealedsecret-tyk-stack.yaml
- tyk-mongo-application.yaml
- tyk-stack-dashboard-tls-cert.yaml
- tyk-stack-gw-tls-cert.yaml
- tyk-stack-application.yaml