apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tyk-stack

commonLabels:
  tyk.io/argocd-demo: tyk-stack

resources:
- cert-issuer.yaml
- redis.yaml
- sealedsecret-tyk-stack.yaml
- tyk-mongo.yaml
- tyk-stack-dashboard-tls-cert.yaml
- tyk-stack-gw-tls-cert.yaml
- tyk-stack.yaml

patches:
  - target:
       version: argoproj.io/v1alpha1
       kind: Application
       name: tyk-stack
    path: |-
      - op: add
        path: /spec/destination/namespace
        value: tyk-stack