apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-stack
  project: infrastructure
  source:
    chart: tyk-operator
    repoURL: https://helm.tyk.io/public/helm/charts/
    targetRevision: 0.16.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false