apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-stack
  project: infrastructure
  source:
    chart: tyk-stack
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.3.0
    helm:
      valuesObject:
        global:
          components:
            bootstrap: "false"
          adminUser:
            useSecretName: admin-secrets
          secrets:
            useSecretName: my-secrets
          redis:
            addrs:
              - redis-master.redis.svc:6379
            passSecret:
              name: redis-password-secret
              keyName: redis-password
          postgres:
            connectionStringSecret:
              name: postgres-secrets
              keyName: postgresUrl
        tyk-gateway:
          gateway:
            ingress:
              enabled: "true"
              className: nginx
              hosts:
                - host: tyk-gw.org
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
        tyk-dashboard:
          dashboard:
            ingress:
              enabled: "true"
              className: nginx
              hosts:
                - host: tyk-dashboard.org
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
        tyk-bootstrap:
          bootstrap:
            portal: "false"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false