apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: tyk-stack
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.4.0
    helm:
      valuesObject:
        global:
          components:
            bootstrap: true
            pump: true
            devPortal: false
          adminUser:
            useSecretName: admin-secrets
          tls:
            dashboard: false
            gateway: false
            useDefaultTykCertificate: false
          secrets:
            useSecretName: my-secrets
          redis:
            addrs:
              - redis-master:6379
            passSecret:
              name: redis-password-secret
              keyName: redis-password
          mongo:
            driver: mongo-go
            mongoURL: mongodb://mongo-mongodb:27017/tyk_analytics
          storageType: mongo
        tyk-gateway:
          gateway:
            control:
              enabled: "true"
            opentelemetry:
              enabled: "true"
              endpoint: "opentelemetry-collector.monitoring.svc:4317"
            extraVolumes:
              - name: self-signed-ca
                secret:
                  secretName: my-bundle
            extraVolumeMounts: 
              - name: self-signed-ca
                mountPath: "/etc/ssl/certs/trust-bundle.pem"
                subPath: trust-bundle.pem
        tyk-pump:
          pump:
            backend:
              - "prometheus"
              - "mongo"
            uptimePumpBackend: "mongo"
            prometheusPump:
              prometheusOperator:
                enabled: "true"
        tyk-dashboard:
          dashboard:
            tib:
              enabled: "true"
            extraEnvs:
              - name: TYK_DB_USESHARDEDANLAYTICS
                value: "true"
              - name: TYK_DB_SECURITY_OPENPOLICY_ENABLED
                value: "true"
              - name: TYK_DB_SECURITY_OPENPOLICY_ENABLEAPI
                value: "true"
              - name: TYK_DB_SECURITY_ALLOWADMINRESETPASSWORD
                value: "true"
            extraVolumes:
              - name: self-signed-ca
                secret:
                  secretName: my-bundle
            extraVolumeMounts:
              - name: self-signed-ca
                mountPath: "/etc/ssl/certs/trust-bundle.pem"
                subPath: trust-bundle.pem
        tyk-dev-portal:
          useSecretName: "tyk-dev-portal-secret"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false