apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.89.0
    helm:
      valuesObject:
        mode: "deployment"
        service:
          enabled: true
        image:
          repository: "otel/opentelemetry-collector-k8s"
        command:
          name: "otelcol-k8s"
        presets:
          kubernetesAttributes:
            enabled: true
        ports:
          metrics:
            enabled: true
            containerPort: 8888
            servicePort: 8888
            protocol: TCP
        config:
          receivers:
            otlp:
              protocols:
                http:
                  endpoint: 0.0.0.0:4318
                  cors:
                    allowed_origins:
                      - "http://*"
                      - "https://*"
                grpc:
                  endpoint: 0.0.0.0:4317
          exporters:
            otlp:
              endpoint: "jaeger-all-in-one-collector:4317"
              tls:
                insecure: true
            otlphttp/prometheus:
              endpoint: "http://prometheus-stack-kube-prom-prometheus:9090/api/v1/otlp"
              tls:
                insecure: true
          connectors:
            spanmetrics:
              namespace: tykspan
              histogram:
                explicit:
                  buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
              dimensions:
                - name: http.method
                - name: http.status_code
                - name: tyk.api.name
                - name: tyk.gw.id
                - name: service.version
          processors:
            batch: {}
            transform:
              error_mode: ignore
              metric_statements:
                - context: datapoint
                  statements:
                    - replace_all_patterns(attributes, "value", "[^a-zA-Z0-9]", "_")
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp, spanmetrics]
              metrics:
                receivers: [spanmetrics]
                processors: [transform]
                exporters: [otlphttp/prometheus]
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated: 
      prune: true