grafana:
  ingress:
    enabled: "true"
    ingressClassName: "nginx"
    hosts:
      - "k8s-grafana.org"
  persistence:
    enabled: true
    type: sts
    storageClassName: "do-block-storage"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
  dashboardProviders:
    dashboard.yml:
      apiVersion: 1
      providers:
      - name: 'tyk'
        orgId: 1
        folder: ''
        folderUid: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/tyk
  dashboardsConfigMaps:
    tyk: "tyk-dashboard-cm"
prometheus:
  ingress:
    enabled: "true"
    ingressClassName: "nginx"
    hosts:
      - "k8s-prometheus.org"