{
 "title": "SLOs for APIs managed by Tyk",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "api_name", "label": "Select an API: ", "query": { "query": "label_values(api_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Error budget remaining",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "job:error_budget:remaining{api_name=~\"$api_name\"}",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "Error rate: across all upstream services [request / s]\nRatio error / request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "task:http_response_error_rate{api_name=~\"$api_name\"}",
     "legendFormat": "{{api_name}} error rate [request / s]"
    },
    {
     "expr": "job:slo_errors_per_request:ratio_rate10m{api_name=~\"$api_name\"}*100",
     "legendFormat": "{{api_name}} ratio error / request [%]"
    }
   ]
  },
  {
   "title": "Upstream time",
   "type": "timeseries",
   "description": "90th, 95th and 99th percentile in [ms]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(tyk_http_latency_bucket{api_name=~\"$api_name\"}[5m])) by (le,api_name))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tyk_http_latency_bucket{api_name=~\"$api_name\"}[5m])) by (le,api_name))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tyk_http_latency_bucket{api_name=~\"$api_name\"}[5m])) by (le,api_name))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "piechart",
   "description": "HTTP status codes returned by upstream services [request / s]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(tyk_http_requests_total{api_name=~\"$api_name\"}[5m])) by (response_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per path",
   "type": "timeseries",
   "description": "[requests / s]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(tyk_http_requests_total{api_name=~\"$api_name\"}[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per method",
   "type": "timeseries",
   "description": "[requests / s]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(tyk_http_requests_total{api_name=~\"$api_name\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "API Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tykapiname", "label": "API", "query": { "query": "label_values(tyk_api_name)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<h3>API Observability</h3>\npowered by<br /> \nTyk & OpenTelemetry<br />\n\n<img width= \"170\" src=\"https://github.com/TykTechnologies/demo-api-observability-opentelemetry/blob/5cdeffe4d993d1ac31c9ebf3f797c28980309e90/deployments/grafana/provisioning/img/tyk-opentelemetry.png?raw=true\" />\n<br />\n🔗 <a href=\"http://k8s-jaeger.org\" target=\"_blank\">Distributed traces in Jaeger</a>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 6, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])) or vector(0)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",http_status_code=~\"[5][0-9]{2}\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])) or vector(0)\n\n",
     "legendFormat": "Server-side errors"
    },
    {
     "expr": "sum(rate(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",http_status_code=~\"[4][0-9]{2}\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])) or vector(0)\n\n",
     "legendFormat": "Client-side errors"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tykspan_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])) by (le)) or vector(0)",
     "legendFormat": "Duration (p99)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests by response code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (\n  rate(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by http method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_method) (\n  rate(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "p99, p95, p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tykspan_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tykspan_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tykspan_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Duration per span name",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tykspan_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}[5m])) by (le, span_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}) by (tyk_gw_id))\n",
     "legendFormat": "Number of API gateways"
    }
   ]
  },
  {
   "title": "Requests by API gateway",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (tyk_gw_id) (\n  rate(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\", service_name=\"tyk\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\",service_name=\"tyk\"}) by (service_version))\n",
     "legendFormat": "API gateway versions"
    }
   ]
  },
  {
   "title": "Requests by API gateway version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_version) (\n  rate(tykspan_calls_total{span_kind=\"SPAN_KIND_SERVER\",tyk_api_name=~\"$tykapiname\", service_name=\"tyk\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}