apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: 'otelcol'
      scrape_interval: 15s
      metrics_path: /metrics
      static_configs:
      - targets: ['opentelemetry-collector.monitoring:8888']
    - job_name: 'tyk'
      scrape_interval: 15s
      metrics_path: /metrics
      static_configs:
      - targets: ['pump-svc-tyk-data-plane-tyk-pump.tyk-dp:9090']
    - job_name: 'otel-demo-collector'
      honor_labels: true
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            own_namespace: true
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_opentelemetry_community_demo]
          action: keep
          regex: true