apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-postgres
  namespace: argocd
spec:
  destination:
    namespace: tyk
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.24
    helm:
      parameters:
      - name: auth.database
        value: "tyk_analytics"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true