apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-redis
  namespace: argocd
spec:
  destination:
    namespace: tyk
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 16.13.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true