apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-redis
  namespace: argocd
spec:
  destination:
    namespace: tyk
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.4.0
    helm:
      parameters:
      - name: "image.tag"
        value: "6.2.13"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: false
  ignoreDifferences:
  - jsonPointers:
    - /spec/volumeName
    - /spec/storageClassName
    kind: PersistentVolumeClaim
