apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-stack
  project: infrastructure
  source:
    chart: tyk-stack
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.4.0
    helm:
      valuesObject:
        global:
          components:
            bootstrap: true
            pump: true
            devPortal: true
          adminUser:
            useSecretName: admin-secrets
          tls:
            dashboard: true
            gateway: true
            useDefaultTykCertificate: false
          secrets:
            useSecretName: my-secrets
          redis:
            addrs:
              - redis-master.tyk-stack.svc:6379
            passSecret:
              name: redis-password-secret
              keyName: redis-password
          mongo:
            driver: mongo-go
            connectionURLSecret:
              name: mongourl-secrets
              keyName: mongoUrl
          storageType: mongo
        tyk-gateway:
          gateway:
            hostName: tyk-stack-gw.org
            tls:
              secretName: tyk-stack-gw-tls-secret
              insecureSkipVerify: false
              certificatesMountPath: "/etc/certs/tyk-gateway"
              # certificates is an array of strings, used to set TYK_GW_HTTPSERVEROPTIONS_CERTIFICATES
              certificates:
                - domain_name: "*"
                  cert_file: "/etc/certs/tyk-gateway/tls.crt"
                  key_file: "/etc/certs/tyk-gateway/tls.key"
            control:
              enabled: true
            ingress:
              enabled: "true"
              className: nginx
              annotations:
                cert-manager.io/issuer: letsencrypt-nginx
              hosts:
                - host: tyk-stack-gw.org
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
                      gateway:
            opentelemetry:
              enabled: "true"
              endpoint: "opentelemetry-collector.monitoring.svc:4317"
            extraVolumes:
              - name: self-signed-ca
                secret:
                  secretName: my-bundle
            extraVolumeMounts: 
              - name: self-signed-ca
                mountPath: "/etc/ssl/certs/trust-bundle.pem"
                subPath: trust-bundle.pem
        tyk-pump:
          pump:
            backend:
              - "prometheus"
              - "mongo"
            uptimePumpBackend: "mongo"
            prometheusPump:
              prometheusOperator:
                enabled: true
        tyk-dashboard:
          dashboard:
            ingress:
              enabled: "true"
              className: nginx
              hosts:
                - host: tyk-stack-dashboard.org
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
            tib:
              enabled: true
        tyk-dev-portal:
          useSecretName: "tyk-dev-portal-secret"
          ingress:
            enabled: true
            className: "nginx"
            hosts:
              - host: tyk-stack-dev-portal.org
                paths:
                  - path: /
                    pathType: ImplementationSpecific
        
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false