apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.89.0
    helm:
      parameters:
      - name: mode
        value: "daemonset"
      - name: service.enabled
        value: "true"
      - name: "image.repository"
        value: "otel/opentelemetry-collector-k8s"
      - name: "command.name"
        value: "otelcol-k8s"
      - name: "presets.kubernetesAttributes.enabled"
        value: "true"
      - name: "config.exporters.otlp.endpoint"
        value: "jaeger-all-in-one-collector:4317"
      - name: "config.exporters.otlp.tls.insecure"
        value: "true"
      - name: "config.service.pipelines.traces.exporters"
        value: "otlp"
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated: 
      prune: true