apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: jaeger-operator
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.53.0
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated: 
      prune: true