apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-hybrid
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-dp
  project: infrastructure
  sources:
    - repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
      targetRevision: HEAD
      ref: values
    - chart: tyk-data-plane
      repoURL: https://helm.tyk.io/public/helm/charts
      targetRevision: 1.6.0
      helm:
        valueFiles:
        - $values/valueFiles/tyk-data-plane-values.yaml
        #parameters:
        #  - name: "global.remoteControlPlane.useSecretName"
        #    value: ""
        #  - name: "global.remoteControlPlane.userApiKey"
        #    value: ""
        #  - name: "global.remoteControlPlane.orgId"
        #    value: ""
        #  - name: "global.remoteControlPlane.connectionString"
        #    value: ""
        #  - name: "global.remoteControlPlane.useSSL"
        #    value: "true"
        #  - name: "global.remoteControlPlane.sslInsecureSkipVerify"
        #    value: "true"
        #  - name: "global.remoteControlPlane.groupID"
        #    value: ""
  syncPolicy:
    automated:
      prune: true