apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-data-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tyk-dp
  project: infrastructure
  source:
    chart: tyk-data-plane
    repoURL: https://helm.tyk.io/public/helm/charts
    targetRevision: 1.5.0
    helm:
      valueFiles:
      - $values/tyk-data-plane-values.yaml
  sources:
    - path: valueFiles
      repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true