---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secrets
  namespace: tyk-dp
spec:
  encryptedData:
    APISecret: AgCcSzJqqtgf+PDO9EVJ8ghndx6pQ03gYuK6SJs9mI2P75wsLkHg7vlU7t3LHq94kqLSUFx8PYGnK5w6DUKYYEu5KNPGZfio3t9k6N2CtiyKmMrWmARV1kb9uq1nc795NQ2CYo7KKv3iMJR8NCgFsxxldS8wT7AW1L8ujyd6wth4NaG1XA+ynjQnOAKi0nlyHJ7/ByuSr7qeNm5WQp6h2/p3LFIEdLW/LmMOT9rLtQnNFqo32oGZwQZIgTWMfU457A6Sp2EIjwoiaSeI/MC6jq/9ioG66O+lMIdSJtlYMgbraMNSAeFjRYZRHUtnKOW/WVhMHx4KZUgkqOTn9Z1xyvaOtZxzFr5XHA0FyaViW8V0QSE4AxPnC5e1Tl+vMh781qLTeKgMw6RbZpxnOOa/t26kuwNTxUchmshHXDI+5ykkdxc9fMrL1TF8PWlVLds+bnSd6MEXbxoK+237GgilkAh4izvlYRBBG7WpaLYP7Rx8pRwl+6m6RUBFS39U2hKk8YR2zR4TmQEmJUU44y7zT9HaC+ghmc9PwFEdaqP9VyabdTeKR90ChtBVUCDjGgt+Oy4NKMDPx7om/KpBNbTyEd0xB7pfvmKairhfmRsQyEZ4Nnn1T5Qq6dtl9bgaee5v/5bvoqYc2PcUAvSYprobr0TJtoliOkgZQ7atnX44DOxiz3hBTHshX0/CF1J/IxvA6wBsu1c=
    AdminSecret: AgANiD3fHPiV2rq8k2LECT0PCP+d4zOSjIZSUvy07Z3WLTTIcf/IlIydvkKcpvzwL9qsA6qOeLK6NkKS/abV/sYuzGrZsqAecWy1irnt8pjIMbfXwZOmpCgB9Co+xJBoJFiugsQN8U45h8JIOnM3NTlgul30qlJVSCtjmZ6m5Kt2EJzGaP7u/AHdp20SNzQvGfep2cxsz2wYHVVb696aNg3/w11DZy1vRhFtRb3tbTf3FWAhWpXaJ/HEWYEQdGXVw/Y14S8pCeg1sDlwSY3AdX4qYUu6eelwPRZXYvtLD4WsC8AemWxW62ifCkp9wN+Ba5ULuniqnbuytx1aIbOEsQQiBGRU2iM0y8y/QdhZlGcWSIXor7JdJptvOX1ZS02pYH7t2lJ/rCsgLKm+pjwvOQJr26rG5vS+a8cBxupz27JD9GtR5rpnH3KQKptwoPUvJJi3DYv8DAaLGtPWKBKopC3EiKrfYhdqzZdaJncHQPCGurqPzjLtrkU7UCuTKkpqIUjXa8WMFTzppc6/QjHUR558vAlRuG8zM0GEiKiTqshKoc65QRRCb5LrS5wTZ7QaR5cI61q4DEE1ZJuR60Y1AgVjSDTvYKBvevjUeTpUZyFVosGkUrJnC7Z5ZIYImt6i8PZC6MojKSnG2HCCZfsVIVtc6jLffF/8ms/rwADa/alKPPTkfwOruzTPISfp8pGI28ncb4YcLJI=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: my-secrets
      namespace: tyk-dp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: tyk-dp
spec:
  encryptedData:
    redis-password: AgA+6wW62zGDiYQ78fZ8UZprnda4Lr6TJkTw6xcyZKuryggi518MBpEHGYu7ZFm0i1dQc6ufidou60RI6jBgDhJdXYebZN6VZQoBSNBEOL7ncWZTi6IiVi/H/o1jqXNCPFfsZh37IWC0k0twXCFE1e7C5VGSS8dfnbxyDFajWes8rFDEmHEeWwH0iIZCTuHXie1DNzS+hSoXY7tLpidRLLbVEqk2Gm6HN77GdtY8NbD5VmVs1ZQZbcEz7O+qZ9jEJFCIevQE4uCwPxqCR0D5abiA6gLdRkWbkR45G06eApzDP+SGPGPVb/Mws1mVDRUZ4/+zf8qdShdMXgsw/JMksbmC9juZFV0NE5pyFj+jTscCnk1LhSfnl3j4i59241wKhfzxMaxfcLeAx7fc5pMrVxF7BWRsMjvrxyCVB4r4dUWOOrfh/I0OYdQBir9xXSHarGWvQa6MoPlxaUccKeSwpetE0LvWSIooFG6A2eC7tA4j5mU8EXI8ml711VZ1sJujh7PiR9pBH0n6cjgKQa9fYND5BNCmWOdM0thKG5xUeEUfjrtavsK3jKJIuliptE3FdTFIcyO2cll/ktIIsF6+TjGmXAcB9E4Ex7J1iin7zQQGewkPY5EtyVE+hWpAWBnGfBHvyJbgTg5GFAk7SNpsswwyPT0OtEGDUCFMrOmz8lZdYZPn6oDre3P3yQccdIAbZ2cS2c5s+VNdVlYVsDc=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: redis-password-secret
      namespace: tyk-dp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mdcb-connection-secret
  namespace: tyk-dp
spec:
  encryptedData:
    groupID: AgA6ygPR0ramAXCbsJl8reWiIWQDAhFwxXBm29vdf8kWIsVVEr65uag7DkdgwvlMTNuQPTr65DXjn4XLB1ajM8+j5C6x+0i97otJ/xwOIo4VambNEcY7zlrRHV5ANeGY0piu+EHe21jN90ju417zI9voOzURT0/AdVi17cQIbrJQTU26nr4zjaxw83TqkFFbJhj6ycW0dT7cTZo1OqG+nkJ1ycRjRHjBOU3hFYHOi7DiZC2IZNfmMnYTo+gDFgYEgW/7CUUEP/+lnKQZaRiPJOuA+ySxTtHqT6lfJZTrl3vCPVAzC3gf4uEBncGrxud6fr0s9Fi87K3X3LjBrvlzKBoRzGyLTxOJITcXsnMBBHz74BDaHO2VUpHiw7KECBhRW5AalewpB8EduAOTVVqPJCyQ6k2ww/ONSmhYk966l2NMCICZgP+eujYIzeR+q9Nxr2FNcORITa+Mkw3DB4AMXnV3+XyqFp0qxh+/GQAS9lnUEGdX+T2Pp9H8ZSyfruLVMnUmGJoss6M/S+vdyruP0xq+R6GnSmrWoYOUmzxaMJ3KorJOsSwUz/sAwKoNcaKInLPicpXoa8KnSgDjAomBgLe+ZDZvrAbb3rMKmthIfNfQ5PFc/TMKHqbtu55eHASW14ZEiCyMUKhHQDJJR7dZg3Uped9OfxUWKwnjiDs+tjOU93FjG++axWlVMx6GkVI1N5yUC4XHpgU=
    orgId: AgB8kkfswoWbKEbYp41uvjOMk8AyocbeSZCB/YNHpRAmZ0Zut3R/ycNqvSHl3xnK1XByW0M9BVJEfQF8HLry3K//t1P6ziv1Mv4MbOYoF+41+jloWCKjPbv8OB/tR8RcMlbgbPaZcR2MG200wfWR/B6IeT968oHcYUuywv+GSLNTC5/AksukG8JvdxIpZdeAB192zS4b8cTTEKHHrdUsHLDghSDfkiqyA5iHJgHHlx4nrfWCtsEcT20mJ0Nv6DxsTcuUppouWyky+y9zXecuHF/3s8+zVsfdCgY+CiLED3J4ZeYp6DQ613EcHMlErAwAW1hhY094ro0JIsBcQUuqS3iDWe4rgvvLiqC3NbUxYpf3pJewkHq5bIgY3gY8RoFXFYZM2aLiWSTnXRwRA/54mEw5nNGwucniKCxEN3QIP00kyzXXwUvf2MGlB24ZkjzabC6hxdmvZzw6nq8rpcZBb0VvyXQXgdZJp9zw94Rsqkws+N+oU/IWQSdH+JUow2WfzVYykmpf3jqqa4A6kerw48343MbclOD2mRqfFtkL7lJkwp2hzd8zSqRv80J2SjL1xzCNcjzcuLjhmbCjVV3W0x6F7dhwVmDKJwuWMds+icYxdWr9bNnfcH0sw5jN2UTED18dFwPY3VTmoePfkXr9N0iPOmTI4dqyl7mnS8Tv27zdWLDPP+W4oZI5kSt3AUWb0o9894LaB8K5RAQXqa6ztVslga6svE5v+m0=
    userApiKey: AgBpzWxnTS0eO1zVeDnCu0HtXwfZiuYt3Bm6DSbEIbeK/dJTHJtpSNJYf3LOPo8jidDuu6KwkGejDmkM7+Ojixriu2UaotQONIRUSC8GQSb1hta7DxPzuIry2BSe22FkjsdIE4Su9762iqQEicqKhiPLq0WgqqTGwnbeOlYChmFp2HQZhC67eYzPrpiw9BdhtdBefSX4YoGoqMwYwYEbXJajtw5kFncVlsNzY0rUCkw+MTObQLmVeskLfcRvRlqUgpqvjqFaoOP5xBwl2kzNSxpRbtywRDReNLbKAyYEoGDNhR+nX92vb8ydVQhy/iiGmfPKTJu5tYDoX+Hcpskissqw3MdEmfs1zNEyY5OQ6e70v0wBN6PLbepxsNyTeoiI93uJznzwOLIyESmNVIOELj3fRPqKsVH2DJrrt5Kry8UIwRJArCvTwKcHkIL5Ciz5kyaPaXflsNxe1QuVW3yxixc4CadDgbm9JeUjjXhugSL5jS6XhMquEpn0SEqs2VaPjB0ceRVUk0WLLqpKiU61DxOrPXk8LFTltsRGkHLFxX69byjIpxVvq0FAAwk2ZvwF51KllI6t1U+sy3l2EZtAIVAodzyNC/GfjV6fwKTo31ZRAfeShlxwjNZACbyRW9Y3VSqj+cPdg+hKWsbko0JdYGTJmuGz1WVVGMQMDp44I6yh/Wvq4Oj7+MtBuV7VUqqbf0ZzCYEsN2Cwl7LiOjfA7vopLhSCGpjx9rGY6ygWlhoxyA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: mdcb-connection-secret
      namespace: tyk-dp
    type: Opaque
