---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secrets
  namespace: tyk-dp
spec:
  encryptedData:
    APISecret: AgBmpMLmXkC53xegt1ysp8yzwCgXNQuHyyu3Irq4JK8yec4XFT4dZCINZ/X/g67JqjntgYubd9CkBLhQjd3dMUCm8XRrjpWN/t+GWZkNzlhfhUln6gBKRtsJbZd/6DoaqdZcPcFFZleQQR8W2/bIIrncQcEecf6v0Wih+rFDs1/9463mZmaSATZVfsdODTvmN1rUMB3vpbLdR3gBXtIUDaGtvm7cy4oul0jk3AUzprvQ05YMQAY4C3P8WNbjl26npckUHaHw6FrTT9XPaDXV5YBEwLvhebg2ohCA4DWCKcDzztiVU0NTVKCxRBQjlFtIlMUe/A0dUgCcRU8UVscjh+TYFWJWA3pMJHjAClm1myrbpSnmZzc6IKwCuQ8Ekk5cYgEYJ41r9wo0TYRqA4kSRdC1PnSKZnhxQ3GI9ZSiUivk3+BlKMu1QjgchPhmrbg+t1toPzvXdh+DCMAbz/mQftd+WRIDKI/oadiEMhKZZPZeF3EOI7sEC7oQdU0s8lFkEIvTjhwZs9EqWJb0mQxKCbm7K9yRFCwaPba763JWUL6JAgKVkRovRPNJb/vHut/5ki4YcnRdiuGF47+ygePyifELQXKfenYjYwPexUXQ/eNq0c/qVHcdSUzwUI99XPOX338r95I9XvZkRYMLskza+zNkY74aFpwIAj1s93MFu1KD9qg/aQFftSb17tEwAa+kKQtVx40=
    AdminSecret: AgAoHsspJYdrJObRoWOBDAiFGsI79/4t4i6aTMrEdLaIkAvfLDhnvXKhe/9o/h5QCDVnV92/EJrxxwcpSujczNKg3LndxBT+jdeQhyMWirTx6mx/Wk5cdxezEixspU2+hvN3qkQT8N44h+FlHGUjvar+dmOuzioJRHND1XC7rqLs9BKOOpUs8Atl9joTLKHn/YmA5cM4AxKngp5fYihtOCmGv7idjdPuHFjfp3IJ8MQPzFM3HEQF2pn17i8hOQWp2YkNw6y0f/WBn77A8NzCrnA6z4Buw8YP3KAlFNu2OnjL3O8RvA3S7p7izOfY3aYOcBLB/ehCXrs4QOVZsBdgqZoNtf6+/lbBSpOMZ+I0EmZSew/qTaBo+uEZQYFAbFgUYhXNMq5WpxBe9LNlxZDvzJLre+QocySyvk0lLwjSkGt96ShYh5yWBxEFQCAqWYVlQ48GT6kybi0G9/UeH3vYIN8rXDCtbX0Z7j9qO2/PVKz3dimWkSPvB6JwJGYwuFQ0APm5IOWuc+wKtsSjITH+K6EAVA5Kt7glb6OGjDjBpq+CEmEwIySyNhXd1YuEf6g7oAfjtNMMfredLA2rCrOrSUO0eSNN1gdoVWcw8JlNn7ZKRiU9Ds2LFjOjQ+ClRZU/jFGd0CSY/ltUgT161H8WFJeCBR+we7kD+64HBRdlKF5QxoEfEva0eroteOsCBoaunrbzBkq4ISo=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: my-secrets
      namespace: tyk-dp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: tyk-dp
spec:
  encryptedData:
    redis-password: AgCPjS1kDv4EM8bxB9w99bLmqLYDtd3VfelQiN0s0rGf7MX/bh5BNOnGfHcnla2VClcbdcVZaupCbV7IAKZIiGSc6PwCghkFVn+hDRwnvm+ZI+QaA1QlOCTifFRYG+ZA+UqB+Vpbixm0DTh5TG87LRvpySdCGMDRhlLbDz9feW6L54tgFNeKRG3un3xA1DYcOxLoXK7F7DIoH2eZPq3I7HOEpTuSFyW6iM+b4Ueo8nYZs+IMl9Jdx8CKEbgpvVUwg+1Z9BWm3LiePpPjqhlpxBxJ4xPE3DPhnm0CP5Nz20ChkVjHp1StqnOKsGmGqlaXCRNfhW5EskTR03ozQXZZ0m2homZsKBP63uLXbfr/a0gEF69qtrsSCRRbbN0vIWKr9oLYc4MMzSPg193i5ihaTaXlwbofW6R8POeZUfuk3aH3Yd6vyIg+Qav3U0XIoUhbu4vBnJEcwwNK7cgZ0AaMy+2SX2CWQbGTH/7a5tBBG2lrmD8OAXWcpF3wRDioHCpNFFlkHyYeTHiMp2EDOvmskKEZeCzSdbteIjXxUVNrC7HfQ4yPQ5aWleL75rZtfcxq5+gLCaTt4er8MwBUHQZsic8LqlhwsnaYWRpUQRqTxFjbNmDoChgDhWUFXKRhXQc3DpVL7nguLV81Nv8m+LhYIWVWth9XabJe4gssQotd7ZU23/WhIGLiSeTIdF47GQISBeH9zrT0DfWY7OsYLek=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: redis-password-secret
      namespace: tyk-dp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mdcb-connection-secret
  namespace: tyk-dp
spec:
  encryptedData:
    groupID: AgAhIjiKrQnMICCRYy6jfNfPnsQcQthihg4+oHYPHlpmU+6L+ybbUj2KVVuJcrBMWQc4AYRWGnebUOBWMCYeE7i1WOTFNRjLmgUFEe9yUURuRVpOOgrFiYQfHHRSi1kvFxZvk4YXSBYBpb3lcswnDN4v+zZYCgJ4hcn7lysrnOqTZtKFx3jHWmw2OywQx8CBdSf8uniZzrd4BhzB/++MFTc1x0wEzyvmKT+A2JpbOOgvPVeOjjAZuMvBaJ5RzzzNJz1ak27vlWklGe7GxUa1HYsjqMHkgw6ZLvvd3TscyiDWMYJ2VF6Z6AwDmcWBzRwZnpGdNZi96cGOFJ68/QLj5KYDj9a3/vOJZiTx9oO1RpH+oVtw6SxEjE74rsJqA2PTizmQ25fl3RHDTmCNG799mueRjHZ5q5nwBAQTtZHEJx/u54ag82jUNxcXhVxCVL6/060+69jZq9Ianguo2FIFdcP/eUbf+cShx3HTn6tDSGGxgLIs7PcWVbDXndvtndlxcOKw8yTIFwhTUUIvuvoJiwbubWIdXLxK/ds2vj22sorkC/vOdLWMoTSAA1Ah/ggtG3LJns6yoT1NDR1f/9ss9t4C+KFcYyslq1Eo/noHhcJCdk4TWjQ/b/bZHHDo22u7NCJfnnkESYOimGBt21z7OFhXg1aaXlAzUWeL+t1g+Tl6VLWCuVx9BNUG8uNXVeJzanz6ZN1C6+U=
    orgId: AgB7kV0ge2yRx6OBuWCN3wPk7ZTpLZZUsvuDe9jAk/mBJFWoBQRw31WrdWlDu89kdL0pmxQdZ4bkC98SYG07C78jacJOhvUrv2U15uYdrMthX9VtpFaSmopB+bFI6zjswcISN4j97AAQ0fZlaAfmZJQ6JzBj+RyL6bBsNUegKljJGguNkqCDIKX3bMLapoPSSXhBqjhu1LDiT6dJjxU48xI7n/scc5tQZ/k7pVxvTjPw6I43QgbEfHrG/wEgKaoaGC5hLR15Dk8DTExHxTlcacS++aYlj9t0OCK7SqkFjdrfgcBpCGC1XP7Pa9B7qPwn+ySHoZLMfPb8t831XQqxa7ZBtWxxC/wrZDm8rrqp2QGNyeFkCptpTyG1gDiDwnHhfQUJ/09tXzM8UG/8HzHQHwwa7Z0bxBcv+QsiKUy9zFF7wskdc+gh/7ZUYl739+n3clDzsGi7rDvuggCR2IiRMqIdgJ2Z9ibEjE4eqR3IgCNhSfHFpxDzVv2GBUWGQ04KRDa4j7Ov6CJKigQV2nOehoKXgAxd/LPyLnv4jMighgqQXpkNNJHRqR/uDp10/zLuFWM/Kuf7obwTGzKw1LYjMU76ToEK4Cduh3I7+iWYxQO/93jzlai4MfqhRM7IzbatYCDil7N6OUGnw0rK9X1aJusxvQy4IGuwukgyeurJ+9byM8nEMS4uWwf00Zmg4vDQeYw6kifB93k93gPCoI7rNJ6HaLLZLIJObHo=
    userApiKey: AgBSd39gNgDidZkHU9rj4D9wPseCdoolMqEObwEgwKE2OxizE2OX1LtlV5mxwOw/R/ZuVMz9gnTz7+d15UhCW+iRik2igg5ZmrqsSmLj1TAVM4i3AbZMtWw1kNeQA+DrApG1HVJlqvmpA0ROvvAWg0BtrxkbFDk0qhoueLXlALFODrpoIKCji1JjdfDL3UKv/IKXtX0aGehfrZXu+lJuROnz9fJFFgLey5Gcj/vt7WxzWxebC4YsieS0zydFtwrAChsHamRR4HMOwDNKZ3OLUAUM/Jz6ko68YokPGI1fxHnsFjgzRZmihyWDu82Sf5MQ0C/j7znX3HdI4zKi6JcJ4+PHIH9ux8NJRluGlqbrvDkkINIieSxkzw6ZWrKhGucvvdDqNe1R3Ssppa8m03oc6H3GO9iK3yCV/LqRo5xK/yVTlC+CpLF1QvW0/CDFAEgZrIFz/qU3fFHbueka9RPBMPIAoK3NyO9T7Y0QlGgZlnWS4GEZdOusb+sjelPVV+Ne8NQdA+bCgo5oropU91nJs9kmkUzEhFm/L9OBUrHL64B/6WMxNOmk4822ouaPqGIBDlHSw7fLyyRWq0cDjpEavdok8Hqb75GjDTXarvj3rEW0z5UwfD2ZTGcZbH1eZNmJAWXRSSVIoDv6ukuyekfmIGQe4Mh47agfELdz8bm6zpkoeIo/s9OztKW1zsZqxIFkQxpLxdU9D1Vm0sA54ooYXOy0zDaBGrtmufhsyvcNjttfTQ==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: mdcb-connection-secret
      namespace: tyk-dp
    type: Opaque
