# Here we are creating an API definition with basic authentication for httpbin 

apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-basic-auth
  namespace: httpbin
spec:
  name: httpbin basic authentication
  protocol: http
  active: true
  proxy:
    target_url: http://hello-httpbin.httpbin.svc:80
    listen_path: /httpbin-basic-auth
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
  use_basic_auth: true