---
# Source: httpbin/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-httpbin
---
# Source: httpbin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fastapi-httpbin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: fastapi-httpbin
---
# Source: httpbin/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-httpbin
  template:
    metadata:
      labels:
        app: fastapi-httpbin
    spec:
      serviceAccountName: fastapi-httpbin
      securityContext:
        {}
      containers:
        - name: fastapi-httpbin
          securityContext:
            {}
          image: "caroltyk/fastapi-httpbin:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"