apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: fastapi-httpbin
namespace: httpbin
resources:
  - httpbin.yaml
  - httpbin-keyless.yaml
  - httpbin-transform.yaml
  - httpbin-basic-auth.yaml
images:
  - name: caroltyk/fastapi-httpbin
    newTag: v0.0.1
