---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    APISecret: AgCTH5qpU8orzZ8jy5QCCM/5oYqs4wpbeMoNT30DrJ70/CFd63doJUPQGS5CYejr6qspcFkHelw0oOiBMA7qJw0UWLuy+PdP013HGVBdOJxKEICaO3jRG/c2ttPBLhVRI4aZVVcXy0hQtV+JPdyZi8MUe5o37jzUTT7PAtsG5xhbAUklVj85Dben3ziUMqqnDVbcj1BHy2JLncH/bKXEDsW+UptS4Kr0JmJNjuj5vpAm/kLzOyrj1thXs1PBK97sG0fAiNCMstAjt6vLUks7DgFVxPW4G+hW92LtEYF+OKX6hg8RNXTc2PWek2lcMV8lum1Uni7IfqjUI2bf5jKKkE+Y3A40wbO1dIhhJU40BA02AbjnvxhyjzIOd2YyobrgLepDctBteCafXNDwMEE+BHpvj8jFyHiKVPQM8PvswS3BEFugKJVyJAWbV77oPS7P0x1Zukiir+cYU4du0hyC/dbbQSaZQP/GjJVsyWwavTB2XBbmF4wE8udIlNYkjyUfs8PBXyO7ZE2vxTrgSqicOxLkUIH/i06fu6XjpPxRRHcW3ERkO0rsV622SLP0NpKSWBa8DGA6qfNwkELUt0hk6NCwIka2YmsHwYNWlsGs6UV7z0PM7SLPnZeIGhftw6HE+bsQT2veGzkF1sMrCZreG/1S700LdPYQEAhjZfzZZjEH/OTFRB6il2bZMWGFtxUF1zz8e5w=
    AdminSecret: AgBXTg2LcKQzicRHUxUOf7xOODy9yGKhXG8Z8LeFBv+4H3utWGmTqKWUDg5XuEai8WOxv6L3cKXL/iaLzydQkQDhiiXq0/mv33bEc78kaAG2bUTw9TjhzXMYFbgAXOz7/p0vD+zFh11cWyNaT8BSto+y8fpz9WwL8a6HFJlN3l+Wa50EEiyOgao4tMSaubohOtKGPXvP/J1AzjWiz4EKhDnO2Ya55cVu3wzcshqF7zwDta9qqIrHZIBHtdISgTgN44QuIUiOKY+8ZhARn5MyU5Gunt7jw8BjvT8lGMd8trs808ydRcEFie4TRUTukUlQ4NR6c2s7L4vzS5lFpUWjhWPqjSKo/KtT/WHDXdqaWgj9YF7xxCme6/vwdzqTtM4GeHzv79j0UhImc3fWVr2hT8yvAlOAaNiKf9owDm57A9hHSMObQaSnhmKWlRSWALfjhSiKDHhu5U1N+C1rMP5rycmxHks0c/WlmHQp7oQROYehDNyO4vfcHTmJNLIl3UYtKiCYt0aw2qQrBt9z66xpPq9YZzOicjL7DnjCr63yzg5FuLeNHUxSW1SHVdG8qljFx2qoHCo7qxeKZoR/00LSgfkeJRaNu+tjB+K/T9/dwZM39yTNyf4sRqdm+9wT8/zxdUPb7nilh3JmxcvNpZ1HDimEOe/w0EE4FkvfkqUzxdzeZK33E4E/UNJDtZ4iVpiJfMZKh/wbJ3Q=
    DashLicense: AgABMvt/P9TCKDEazpIbHG0KjFwulXufDN2D+W1nei8gXWIqYYYiYWmSFfnkg//KctqmNcn9MUjhPJhJgEEkJ5/1lwKwdpXYDgvJDnTWNVcuxB1dKzBSXVl894F5VoUiVGpaORAEpMCoVRpg57l2y34PWYdWT9QYhnTydGWhbL+O5JqWym+447qRwMOCrepAqFRTbPQu2yv3iVETPJSNfR2plwLgfUsewof6DSwlSrgjULK6s8/OsjtEGmecilKHbrqUFfl9PzDv6r+VPm5R427mYkGj4E/ogNzPJ95czektAUiwBR+6IznketpLnxCUnpuk8zjXXpIRu/9wCk3P0wpXXY95T4hX4OSHEXg2mk2thbNok54do64jTW6z/74nN9Aww93gm3F6S8ETDhMKGfTJBp7pTLX0zKlhG0UaIhU140+eLn7aE8ZRpOhsBOidJn7B8c2MjhBKbbhgGLhih2auSbKLeairXHAi5imBeJ0cKkFpeWjBNbCSZRUQig0HIPz76ddda6sSHs8KMWTNuKesaxf1e7cfD4jgt173lcCF2UzlAb95lB56NHVidYvTW34bTnJHrf6MR06tRM/1uYy763vXAfRRYkq15dQ5zDDwNZ4U0ZrKdFTbgz58BaQbh/7Ju/1tbWTEKhJiqKQjN52lFDEPqtC1pveeacWYeFHC5l5OqusOKibWM79629s0VJMo6y/w8XbS3o2sKSJCE2ji2cSfZ7aPXPkvVRUyOSUxT3yHqVhuPIR68R0jzuCnT7xHMdhMvdzKTP657ea62aVpgJNlLLVjGoVNd9JZ9/sQXtJUYw+/o6Xif4FlJmTIhquFNPGy0H02uCpqAM7o4iZLXvjrqiBnupb17YbvEaXfxFH2FD4WZGnvL/O/lK8sxO+TOyGDY2ZEeE5TDp0BLEykT2tY6o0u2zZlB0twVd33AESIdvmOk5r/ZkGIuT/H5t3IaGsAmi3fasYzny/OD/rKeV1RTCEIGoPYShHXtKZEhzV3hD/7RmhHJDCOFarLzzIEltetFtcD8/PuO03JXj2fMLEx1yQKh0mKfa95A4PaOuAoAG1MSo/A1TqPN6Lt4XpIb5Por1yT3rGTDLOX9/lZcQDfskO7jSG+ebnEoQGL9fwMuD0uKM5MMEfco3xnbIR8981ftkRqt0Pst0a/GX6KZ29XWvmPZErr3dsxR5FEZjAl8xfA3+cOgLpS87oqtzfmS6sj9zWYqjnPrlsx3DfEtEM9+tmip1DU2Z3oD5Z4FO8kALAvt8+23ZgTWmJ4nLVW+bBCVLa69nFCARDFAP4T9BdxqbTIbIB0xtyREdb6EJc8cgt7idq7BwBuFOac035IlbuK757joD+tM+S56uBsXYW6D0yRl+5829ENs5qkJOmG5btU0u/Dj/Y/lCD4lz6sCSxWyR6QWLENeDuX7LKhnvBCnEbAcDtuP9/xtY4MRrh9nouX7Ooa76lmwyBhUAaHSilHd+5y189Gb/iofwfNvK7/E/1MFWAJO23uU0IekY5sW7UlHC98TApZGhxaOIQ5aUhY/OLDp6AklDQ5taAr+v/7QNb/W7q9FYeXnWKHYa1beJZtl7zwT+25TvNB9UO+0pD/tuuX9DjG503l+VsVZIDpIQia9LCZ2nqq7nw2tBLJHcQWD8thJ0e9NeNsqqanTzk8p2Gqh4zwilqcAJXYMosu8N/OU2FR/p5b71Wl/dAqWWPtv8u1n92O3CArCrCoQUTzgeFv6Xj3iDI8dxpH1Ew8OtlkgiFLwqXWB2roI6wcQIMeBE6a6WwFfBweXVHSW6s3oBUHYKJ85m4r7pRw40rm0gvixbLMeIq3TKbkS3qiKs08Uurbc/pUEekpynzuAPRZ5VLJKj/cj4H/io/HUgJfbwbsTE0IwOL9KYRe0SlKnzweRnFeb2ngRTJ/DO79CSvoMD6bBUKLKhiE0DGm1nNecP3geH1X/8mcagcMNr4sht5mGxHKwt+F+AwtmE6t6vLtbzP/3mHeztcErEyUAXWpGpfOS34D8P1LrixrWVq/xnrm6QZHADf1gKfDJv+oJpmr6JM6tPEiSZcWQ9SpLDKt+1MrtTvnei/qWn8aDaSDYFXoIZZuJnTrgsGUy6nHa0c=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: my-secrets
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mdcb-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    MDCBLicense: AgAmEN/lZDQfdnJit8E4tb/4Bl5ltUU2rh+DBaqtDK3r6IJbz6Qid+Bb8YpbT1z09ejYySjvlDTkIBGN7nynkkB0mu43m88tGQkpn67bHTc+lVaCxEMmS98BmoIEwZkgw8wG8EVm/qFqODwjn0XsmD9g4uRtPyUzmo6qT1CLP/xnE7kLZPrmKrZdxanj91v5+EKJ85eVhuqZS59ircpQ2f25McYUTB1+D3NGsGmpRZf7z3dYeWFzbinYAzop5S1ecz+2++lrJPWzy2CKQgUnmBvreZyXhr3IvxrqzVGHk4pWKjIHTDtpw+6itZkK0kWvIsSp45ktLYMCR2QW6VViEN+wgpLj/7zszkbZflqrJGnVKiHnIFtrAlH5wsjMe9/KTlcP9Pofk8F3JVvltNMlH3c521whPpgnRAdMZWau/aT51Chy594YnH/pAVA7E6Cak2blD9fOiPc4k1ZBXiA1SO+dwzTfufmO0NflBSFfLZHUwIkOeHiK77hyMlf4SASF/cVirBUQ+TQ/TcWmlu1r/u/vEM60lM7OkMI/3FI1zlgl/FYfnnw3SGeYpW9tAL/fqbfyaBsR8AhKQDeseuBQn7VdXYuH2NqZulE5m8Nrww/Wj+51xawrM0/8Ag4FUjfBjxqXMIpl9zS8BPuXAFxMl6eBVgQUrnJ73Wo5SBm0OeXl0LRETv+dWSOKSChedUABbyLXVR8QyeO7D5ffxXzu891EfWHhCHkOftJVwcrA3+t0nnElulvPy4t8A/kX7FFYs7qZLC7ToZ93oELv8kL2ggMCNcoSzu3VmiKHx4PMzAF9WwDlrAUHSdlOZzqP71v3DYvsA8ylgeFsMG4Mu9U6IBZm0168fPr4pCjn0U4McGPZWpAx68Pz/Y/UXp9uQfI1k7eV7MRu1gLRwgm1UWjHHUiyYl7X1idb55N+f0fagPm23vv3gDe/L8fqXNv8PuVY9Ug7DOmM/y3STiYwQ7Cm+nA83INefb3YTAbd4OX/82K/6gKW2VcJDcOF9C/sz25st/LD/jqIsV+Cdj3Sug62YGNIRTR1FFtVrG15NDmzFfFrbHuKQ7QN/nyvU8WiEcjdfxLt1I+0poWDyrNlSdsAyemK7NwNVErQv5yvadtGK3DZNPkDXuNDTDZxoGBifbFmEhtpbMVqBWHKbLKnU81NYBThoXjl9fUWqQfC0fTHagQOXzWCyas3crv52Hv1yBKvwSvFA8Ef6Df2pHTFhpwJQlA2TEDAT/F6rDfEZxViDwmsfHQjxI2ep+IDQO5qfOxfbvvCue52Vo2PRsJ1nEBaYNIy8SpA9fpd94YsLesiMiRiCj/l9IjwOYog1OVaNqDgfw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: mdcb-secrets
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    adminUserEmail: AgAKpgLoy5DNpzZaJDYGSLmwnrGrRqig+V6XzSTdslBmvgBXGILWlkBKUzzairakTOg7Spfq+xDouYfbhxM6eXjmvjxPoEHPXD1CDWYcuoYvF28Kpi87wnTVe/p7Qso7SnM83fo2AOMql7+wKe5GKfrhCLNJDpXknxufXFCjuE5GAc5Mpm8wIdSsiPGIvLm4wR+HT7uvl3UmfpRwayIBSpzI/7kSd70NY17dVt+RGB6NaSutbQvT1uUJHNF0VARvMKQ4VPrbmAo0/iQv3EktC05m3EipIvH+a+WoERj0q5XLBiyVp1qhN6G5fFfthSE3YM1uVFda0mYnLFwszCCCNgKF6om7oPMsVOFuQhExEe2bB+jbbMcgUhUBsVXtJ+t6fMaQG36wpTXZqrH2RqyRvLVOZByw3/EoWO4rGcUxDOE87Z6mroETjHYxo5YqOkXOw1XzSob02Zl6zyrU68W3JuN3s4AkOfOfpyhzX697ALeHhkTlFmQOyeIRU4/huGRDm2bkF/XWtC49SH9sjtUFRkLPqrP+fHsSdus4m6dmVCOCqIhXea+uGFWaqogNaKnEgSKkcQfmgggglKkT+A13NUhd66KUyxvDHxAnV/NrzPJDt+qYXRKyhxnjt3CUAdIQTEFuslTTbK6gcJMug8Ab5nOtL+2VBc5Iobv+qrfAJOSlvkXcsbWKy7EfJM70rxHeVLIGSmKF4oqEkO/84iY=
    adminUserFirstName: AgARP1OYTCy8zhyFu5PnNeTp1RGoLaHZIKNpsxerY84wYTvn6jkex9UaPYiZeXYFF9OY+Qggsro1tJ1ZcvIX9TF98fwGGvlnAhOapx+NvwNKMa4iU0I+EdBJniLyxSoOIr7kRBF0wM/yPQo4oQmMyXVP8ngbEsO86wmUntyfSO6A6wBkdTaj7aD40hEUWwq/FPiKqGWQasW+L3djmWQwAdtCBaGsXimbiv0v7cqQhbXXIPZm/PDlix1n3LSAre9RlV8ifPu/AHB4E4CU+s7olcj2LFDdn/m9SNdFYj81Sho6bQDGtRBZSVunTQOLnahOsRO3lajTJ+rf7FGrWZEwhSoZ7qI+UnLPfE8voe+OVMgorAso1SCXMkF5FsnCRKMBy8pE+jm1hgh6yaFCkO7kzDpdqsTvN+ai3rLbQtdohCsajC81z5n52u4VWVlArHPsfVkAhC3Ih+vs1JVRiVP01+Hoflsxnwgwnrq5t4MDlUskY3QDBcJ/9yZCmpQ8beDHux8l/WkJdWiIQ2wn80uD0qjCIjul/F8gxLOks4d3SzwPiJxsog3zxnf/rU9HDaB5jT84bzEy7nHnMtbmG0UOm9HcUP1TPVI/NILJyrdQqsdKYFir4fLl55dw60yeF3TZivx15SRJy6wfs+qUNtLcUDSc5nG+36IfMslMMWh/A/Iy7PhiAJWjjS4shfDWK1Q/dmzYm7J6RA==
    adminUserLastName: AgA3bFV1VuGr05kDNMxeHyixCr+6xQQ2eXyiOuHo2kh0mzp/oa2I+Ag6Jm/TdT6YH4MkBiX/6V4Mh3ms8ZXRdg8Vb9TvkRgYUjB1cw4C1Jo6VZfW6NdavwIZNvn2ptM6TscAMorbGcjTR/7CRy8QnMq/EzDE2iefYfKYLA3NwWmVKbvzM5PnqPoyX0rj0YI4cWh+Idk0RdyUsnJSnNQ9fnW1PD+IuYNJVE/MUhEdz/uMAbStTRAo4NSt9hOzNdKsdOffQT7zLHWEyaLMQy/Vet1Zpzx8ID+8yH35AVuarx4WRZRbFclfZrUj8qPi+4OMrDjBZBBhpvI9sARAPpit7wawRM7mbHJAEHFnh9y29dsln1rHoFgPM+vBw2r61HybrjXUvmj+K02Vq13WgHgXoCEMvJlnPNohSpj934YQH95U7xsFxGS+iCfFK4hht1rpl3lnpDDfrsHP5/MBvPdgog/Fc6zBy/jDYkrjo98J+aDDHHc2qpJpBMwiaYIUQN6e9gG0gZNRhKtUhzqPH3e/OzjZr1vnllYddURVy99qgUzpcB6Niw2Ws3lM+7+ZIg8nCEsjbW9HgJiOCGDR+1SPf6iLa6mO9w92c1cVLocWqY6i9Er3OHKiSj183S5e1lZPPmC6ujMB6w68YYZOfMSJIr1HWfIec4X5XNYrbB7hJe5POdO6tEwxrCDsIEVzOzOR9mBqhVX/C/E=
    adminUserPassword: AgCY79JFGv2Swhg5RKYUVLOCK44bDKohLgrzhWGFkDWqyElbv313G4G58ngm87rWOtPm1il2cd7/GIQD8ex8uphJ+VBx+esG0rjxuSojjhJSwAh/SoR49z/rn18HpsMKjQsO+VFeJkmn47h69KFbRPezDciPJHC9+9Se20044MuAa19KHHduUy1QcC/49xg7nrCfTpl1LuVu/fcIk8NIsIqo9pxmQJPhrIZs+p4ng9FIfrU9og1hjL+wwj201CQ0E5WeBhWaVqhjUAnf0VM9JyLg/iAW420StfBZlx0wHgNhaDrJ9Xo+aVlOYmFXOi1He3WZFLO/y6805g0r2IFjK/bXDve5fvZGBnvPUZJYHNh2R15mTnVoEd8OYcsIBedgTn9zPTx8/spQwFuccAQkSUpfEaBVaDZUC4sTBFOQxlTPa/t25q/byck61IckzwIWUU2/vTXHlB368lthwqTxDILldF/jlxi//STaDPHrvGUgQPJ6n1m3Ojet5rhzRUnQbwZIMBBekLw1GcfnJoa7ep7Ox5U49ihqw28FzY8mRMtlN5TPQjM7t5BGFaHT0OfhRg6x3JRrrpMOTj7Ap1cIgnsVkKiiec7pufYNxUUrZnY/2l+CRNndjRACjprDDFSV5LL22tZv3ZQ+To3Fh3pvlpKWUw0xr8XIv0eUaza8Q6UBNU3xHDPckdgpxiO7QYor8TFSernsREWpMuI=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: admin-secrets
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: tyk-cp
spec:
  encryptedData:
    redis-password: AgB+FR0Rr6H+3pfsGxxaeagXoqgUE5iZg4e9ExtAWstq/xftBbJkoTRIC0ghzjp1UPWb6YXhb4M/fr9TwU+TaB0EljjOjQ5kvFrmGqqAYHUFP7EmPoILaXNx0C76w2fFv7BW5v7uFjvxlPi05uQqB8ysHMjOv/LJMa545YgRHEKaB/4CN0Eu6gl6ltnEgxYzJgBnCaYXHneF6CsKbos/YwT85zXoWOWLjv6MChBcBT9OnGeO5Wp3zWf6a7aJBSEuhd9GrOr3N5QFhsE6ZN97XStqfJxTLwoQHsLxPE8/ZZQJ44MftAfTg7uKznV5y/s6Gq80hljzcoxULkdgnwLzXAp/4REOAgS/hIeaX1+17I982ND0Od/T6at6fewpEgAdcBeFQ+TuVANqIe7XnRre0Tt+aY9CRY8yHNk5Pg9nM/WwWuoPA5yL/pCk0bKFFBf9ugVORE6MThu/9usqUlO7i4REdwQl/X3NN/4AXnKkL1cmXX5GMBfB2RYsJXz7uE8MNYUFdNjDm+4twT/f4/CDCGKQ3uv4OU9rLm8sNzgxdIKbun7TQVjAae5zWxyvOU+Sww0t8J6ePA5KtV4bUumHSaEDWeS5DNuKOp7REiyx8qcTk59OnvF2T1jlDMEspDRHrhPNhchd+VDoAyjvj1o7BuhIy6i6n7iDouuL6OPyMZ10jIUItLoHNi+FhE9ofBRAu70Slx0NWbshQEahQw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: redis-password-secret
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-cp
spec:
  encryptedData:
    postgres-password: AgAOX7fSOH0x+7cX2v4T+FBQYYYcgEZnDxBx5G32Em0v/DeA3fJPEll6G8FS44s6PXEyAVjudl2auf25Uap8GplXXbsKqpiUD8eklQkeL/rYVKoxC1Vn0LJ0SSuT3E7wrWLAgg9KSZcvMtGppar9uDMXY2gAlnrrtW+rBbt9DovhPNyDcxRjccQuruzRpO+YpKzQ/5wNNFtcQWU8SvTUilMmlukSJm61Je7Eq+usF8zTGLkqaKx3hPRF/mt/D6w+xT8hhGy1J+1xxvVgV2HHdrk7iry7xcCrRzmsxuteAq2zz56WdaQphA05rWKdmeVvGxwg+lZ5QvOe4zr86onIzGPW50d7s6mTfeje/LCpO/hLC6fU9HcJI2NpEkWRN6Ja92ndt6zUl4N0z0pjGgI/6YNczAYdxKY3NrLd3C2swXXT6hHDDLeQMaM6P6LO0BC/SLT8WmZ9dxPxJ9G+IICUGaGUywDS2t38ZjeylWQvT2xFpo0N+vOnISop0Ow6FYVzZ5WwC7iGnFMrHoWomaSXhvKbmV3qJgJyahOtDxFvOyttkORQdFzn7eDr5KXsYbhpltvXjDf81Az0vgC+CChpyIPURTL4S2jDMGy+tsYgKHKpS4uJzRXE9QvdYO6LEnaa6TJSddmS49rmfaLN0pRG4TWEIIL4gIVhBy2hzrHTukWXjOjqhpaEPVI5ZHpkm3rTqYD8XAsWDpGEdqQk
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-cp
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    postgresUrl: AgBvrVmeUVpqtJE/AMpOx6knbFWgK5ZIMr6huDDomHVmq9khvoK+ELDEQg2CruF1fvjbxQGQr2FpwFHuBVuGHcrVSmtOHdRK4oyinv1XdHTswcw3et5eXR4WgN1kIQoqNK8bbtMSC7a60c8dt2krFIjyk68P1EfnUS3tjBtWfsNEy+y96TPPtioUCGJcok4h5xpuCf9+ifbJcl8KnCmXfwQVJTEW8AazwtPjcnMsuouy34b9ZhEMWaDlZQfFkKoZb3IPq7+/VyCIMy6QPusslG5fluBw8ndr1fGoRQNPYIM9y9eMsHRN6+f9RSP7u8zXLYtp4td9htMk3oR8Z4xJGQzmya+NuJs3BuQWQoxDqC7033TsjWNfZtUDj8M77+zQHG1hv8V9+fj5x3vbuY+sCsGFTKQBhUiEMZxDdkap8fepQdCzChj6hRTdVIWBEGexPAMX7uAFCvQgRcoTCDXbOSLimlFDwAvuw4SIzyQ/5SjZ1JgjnjKnfFNgAMYcBDFXt0dG1Lrgiw3qpMUCXEkygaWlXb7Q0DUAXHoP3SVVdnz2vEgCriXDBJrpgwAorZOi5759TrzSO+jp7kxni+fq4JBOeIHSFUhLdJLqWCH+/J01ioOJd+n5tcuJNzEabVQDLLy7kR21HBKJye8GyH+PWU0SROsaRBeWYyZpau3tdSLrZ3usJdg+Wz/ON/ScZQj+NF+nTGsK9l039z6nuy7rfnQ4FGSVoSzh1aP3uqJYHo2R15JVFlRldXmLZABIPNItYu16X0T8Pfr5QliGQI+43+QPqnA3AfjbWL+JcREaAoteCFjpbT0b76lffJ/wBfG28NKUCDJf2tArj1U+/4+1LhJIeE/8nHJN
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-secrets
      namespace: tyk-cp
    type: Opaque
