---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    APISecret: AgB55AiwApzWc3iy8LFnUXxw8bD5q7i4V+CNQmJYLpIBPP568uWUcjg6rFf8PX8Bxkri4X8OjFWw8ifWhNcz9maGXaPOBZMJgTDtKLeC2GW5vulg5PlExc/LawFSjuK64piTWNz0A+KGkNneNfCsa9GSg/Chji2nNw05NMuYv9W050xKb1oU7MBpt/za9SRQLxGDTR+wzYkduA+toHhdyJECcXZHjgKvr79O1fkpGaZiEcvo7p33LkyKOIpgDXFfnBALAHPYQ63usV0iXQ6tcbzB0kCTb+UI9Y3DecED89pszOjFZmivHaVISv4nAbDAI9UEtjSkWTIo+nU48YTQ9awaE852NBN81JhxnGGQUwBngroC9VxBSjkR8KXQE6/5QMhbPY57lR24ADZSzeox9k2DGxlJNuxEIo7n3nzf4l/mhkXEvfIXC44w3NhvYLpIfuDOSgEN2CmbUo5jGrbhBBPiWarueDQSIZG6H09czPlZADs4hJBijw7FhWi4OSHKZpk5mUscMpi1P0W7XCSEHn+QjymFBGkL4r0w+vy5YezXdAjiGuO+iGnMSCNfWRtvUbrvig3r8nXhiR7xoMza6fRN3UkcdL0dFOzesjdt8aksFNjzqKALaK2BOWCch2gHHWwM4lZExROo4L100XpKpZonUmcUn5z8+LXYOhxPYaEX55wSBsl1y7oEqHLjnmCeoORIa9I=
    AdminSecret: AgApnFZeikN5/Yc8kc7OsyHqU5hd74C1mbGeaZU5Fnk2uQBDiEqLSbXrgePJkguBx9tTeC13F4m5PjgLC68uRyaZ1IPrGIcaWsQHItpmefYv7npYjlty1TuMdmZwpwcGmW5hb2NtZv3plZmxpci7a8pJCD0yjaAJxJUBAmlcDTF+aUWHUCeGA1lH/jhd8InPleW0gK4qKjplBvyGFpneLsDGPl577ppGaUnsnRqkI2k1XoKREe89huiKf9F/X7EFPM7U6H8vEBI23/BgnIMcpIsUr70EcsEu8nDADb02IgTUrHzoIqlvqVQ+bJZ5zIvX3xrJGTCsqIwEKRBOe+riC60Mo9m1NK167PPtcRmnV2AJcg3PwATOm7Zl89kOl56c94fjZ5nyHBpoxLLFKI9V6TMBlXIQX7Oj1UGE3qNnv9SoONeOJQnjq1Z8ODXmH39Y6aqnUP/4fmfSGkp70P0mjn+EWd+0m2MVXl1rtHX9WGyq3jzNfJuA2b5wqfeuVhghE+6vVTbAxJnQqTBu5uZFmjuwssatifdKLssUs75GxxrsCR9AHdLFhM4Xq/6xfZC/JMi8FpWhkUUnKzUi2k0lKmmDfpHiV9mMpQRz+TlQv5Ppmc4sPpezFjLV3RSbCdZh7+TiuaTAuoLfgCEvHhRlNSLXcbDlmrsaWO2/2uTcFv15jfVNEr+TgVFjw7iLQCtrEm8GAO5DSao=
    DashLicense: AgCOBkF6QDnu0VQ0VcxezX3SA3feqlzgZvPmhWMVYK7t7H66p40Fcl/yLw3zWiB5tKS3W6Fzd7wg0fAPdhmnyaEY2ReQRedi/zWgl19PkV6Kg7zm37BMp682cKO+BxDCms6GGOgafayeDg1gfKJ++LYaCD9Uuap3+kZAnIlzafqsffnEyiTOnY8hwwRxsjZ6A6+Gww+lfl1uqeKhGQWXwLKDAiqanCMufZ5US7fE5sNEnRtGqEE7M03BQoRTRlTA07y9KBxXF18jUH8T/ljunubUxSjnJB6NXnaOLSR1m+5DgRIO5ALd+WpuJT+mUFQ+JFvkb4St9X8Qh8si3kd6UzgAtKtvtZU1wRyYANlPOQoATE3S71HAWQTwDlvWM003hhiJBo+V/PxckU/KYb0GthfyxEF9gHJIKHpd3/Hpob2VwLSIbbok1oIgh5FL4F2+ldeosAS3Q2UmAdi1c/ohTKrKhPoBDZabgCz/B8ywqv+tJyX4cZgeLBkG6a8Q2fFFFhtu2k9joUAoZqK2+YRS+1dVxpXZFnThzsvzMiJvDNm80Mob+5SisWHchaUsFy5kZee9q55J4EqyfXEEWX4acco59TAkF875vMoaP7o1RF5O34mtjeAdvvgKcySikzfvE+1glmLwYvokTLdo525bwUMbhNHM2Zq1+fbWyxnbUAiQ5Cva2zq7YH9XgpEv3qCuEUkbh0c6t/5I72CF8eMxBFCg8x2SmuiEQHUseWaMxJPzPv4p+AO3hyjl2G1t8LyQ8KiqM9iR/09gDFPWzh4fq3KG6Uwsv4YxiN9PEIaeyb3jpA4X/KNn1tfX6Rh7IQ3k7FwrjPeJKfQkQZESumhLVmvB8psInBka7MlrL3UfCrNeSdmftc75T3cp4qtmSo4CKsYExcAnR2DQs/AM9mOiMdbOaErUkZD4Ln07hydCvcVGqW20RpvYZVvb3IOvOkBPEgga+q12xn4clNH4XNM1Okkz1wSj2C/ZoFjtK5MrTrbejnPTp0cXxkv+vxOFRvbkVsz9k+SiM0tfDuSbzlP+zW4uzfJz8+84UzQZzx+8iJ8TxHbieDhfiot7BY601vpu1w42O1V27jT4mKqhTX0i1VfUujTSm+7kAFO5Vp+BB/z1fEXbfVbyXjwaDsXeWmT3MoRFEPvpICs1rtLGTUyH3W6O7ZdVmuM+aTPwdAdPBCuW95L8cVjcqj3vLrLuk6baCiJUPAgNn85JZwxWCOamh1F/cgr/u/3pstO7n5c0LFkA93DxKFrXmwx5cosu0TFwcvC/w/Q41TKWAKEkyJdwVY16bWa5T0cXmg91DVMxgaZGaSSTrmhtc3i9NU8lFyQfkth+Dir57MEvZOD45xKWpMAeqNBFnY1U96BM3MvUmbBUmGaJ8ZSdqK+1sebCk87Ek7XGZyTxgvxaeO6w22/L54uy6sKH+1sVnwy/3z/3dcj4LLGin+eA6EJhoZOsrWsxSvZfbopk7WEAAUfUDJ0aUcqggSrMdlNLYqF/Nrejgfxxc5/z9fbADPr0kq3tAa+FWYZnLolNeQMAhm3AKQXN6c1YMjUKkggqpLAma49W/ijTzbD28EAubQyoeVf3fgBufZF48tOEcXy6dNqKo3z1gujcBMA6EtzOsO32ZaSphfS/E4FvZnqliyM8MYEelqBasmCVqPCCCT/c0BScjl/sT+w2feTwe4296yK69rUEV1GF6CNASDggSZkXU0I7Dm2EbFynD1m/3ozW/odR1ME/MjtqFDVnyN1ma8bUKAvjxpOGcfnT9VWXNZLZRKMzKt+anDEUD2qON36x20UV57k+fWpXxyYNt+COkHYT+3AiSbGkrJQlLhdq7nnCVKXdn6WPbeAjqgxrH7Of0Idpu7KHJBmxYqrTBaWLOxPEFk+I+8KqZ28Hb3/eVr6HYq4ITpW/2Pb3aqRsjcbsjv8TW2qXFnCbEnuJBV5vgMAUE8xO+c6JSPSjzFaSH1BfFMr4OmcS6wD7T/rzots7xw2fUnGHth2DhWVmJaw/Kz8nN+TND1WQznGycqoMwkiYYrEC7Mkjgfbf8b3nBkIwc/zfIUwzM8LY/B15Fa0zdAc/yrMNVADZfHzX6kw1WFjd0wFT0JfjDiEPEX7q
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: my-secrets
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mdcb-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    MDCBLicense: AgBA0so45jo4Y9HMvGxv0cXKCzhsuSkZSUZWRPRsSYzVONVAClRM/TDpzskvBV4kBV/jZax0vdIc4JnOHS2mx/7hRxoJ3j9sf7SZrKwrQ0VFjzMqyL5XeEgdWohV3HioVHvIOXuf6b66yfTuRohLx238J7GB30kIuMsjq3si09vu1xBB9l8HHQtD1lWTo5jTbwoUAV1UGimsRM9JeujBkJNo/ugf3ol2VUPUE/xEcEuo815k3tm1YqnnnKaBn9bl9NTeUxFwbbsD1iun9lu7ehHCem0Whh5Bg7wkDkVszaRVvcyAqPiPwHHGJDgR0bYqoHvRSKAe7B97CdPyGqnNrEzdrNAryuSGVhZHA2mTf5VpPWc9SLkG7XxJ5NU7Ds6K/4nuNpitXqpMBmQK1XppUSlklvpZvQVJHrEN7GVBpI8DEt8aNvW76YNn3xH2ItMRlp0j4Z1bnJdiLIPfquBtWUNvt60cvJ2uUj8K+lLgcsk+yWtiK7BENl5KWLcZYb5vkAw4CLtFw8DJJzgN5Z/fyhQF6jFAMJOj6RAtOdk+Q3ZMosuoYkAe35JhEyAzkRLuynu8eL+Lh1bSz64XgOIbSKDVhIDv6EY4ItEeaGEja6HhXS9mnu3JHdr2NqOG5/7iydQQQqPUFEsgQVFby4MVNZ3sRNvVLI0XoVy2qL+mkXMQIlTQkLaggEWhTb1ADKjZJzgI3tKSRU7PYj8tE+oz5Sahw+Fse6d9Lxo1L2mD5vHMjzCYtmeaSBgvrpVYjfc3KzyGYbXp/n0p8CINzL+x0oIPtQt3SdoKJqucq9MXml/ux42wzwS/hyFXoL1JtNKUbdI7Z5+pckHaEhTV24IHxSbKObrdUW86a82rh2lAaA4LipPd/Qu1R3pirCR9xqgSVVtBxJYlVtS8/iIQaLMPSnXAJNfcz5dUfMV+JjUHbs/NB7y3JztSubXA7kfO3hCcnfHIHkZIwL48Pl9ofVaYGO33FTCF7LsCgqmoAJ3ZyCv/ROPd6MJcLC0xe6+WD/D+8uO/5AcrEuLdGzbddK8JXAQfZbPAV932IyCB8RhHpsmSlfMq4JxjKvpSk/+5VRYF0+qq93yNlqAwf9kaC7+689vC61qdSoD9rshhYoVPMROk9IbYhHev4BmnSObcxG4UTaL50uVsrbAsVPgeuH8KEWC/MtSeP682BUjcQ9xTMafrOnKNnAn4F1NpoqyganqgHaa3TtQ6DgHD9izEMRzt6ZKgO2XPu+t1FUB0aul3N+eIw3poNVJAZHDN6XJr3/93IbwovMUEkp2UDa/XRrf7UjBz23kEnaANUXZjKQyulUjfSVbbzRK8nC52tiF8zjQJMqg=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: mdcb-secrets
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    adminUserEmail: AgBywyWLU595Uhv2zTInVYCoOzW0mvGZO5SZIjtWGah6425olwf7TXvRg+kDwHoBkbAbxP3NlS4qjykGQgkJ38Pcr/hWKWvLqVz9YoqhF9IXVEjwOQUtDJhfNjX7iiqgEjdFfLTNlogm3HB/rYO6dJaZHpomdc0/ThSyEeUZEmMRbHAUdCTjsQTqBjfS2MNEw3AP+IUM0YflpfNDsAksgga9PQVTjS9Mw8LNiPoovmnOBJTr30v8k3QJTmKEdylfgiWabUKUs9nog2TlVwQw4BdOuYAYjs9nVGVh9JV7tjOJCu5RC8esndXEgnuvZLC46ly6ARc4eIQ2bFJCHUGv3dNSm3pubgv/PsL3mZzUc0JwlNteAD3RwCUWGEfItQgBkdrCWMwovfFyDD6QUgyd5QW+gpEYfI0dgONVv9fYz3U1QcTrzPTpON2fTj96FfOsgajS3bAHMjRnxiIcCBF+O7D/iruQApHAHPzEF0wYMAT+LyGcjm1RZJqaN1mIkVaQL7rgpy8RgnyGi7FBW29eYct6/EIe22nuIla+Cmrn8/59+4hfX9P31e+xU25a/lr2tndDFaOgus4r+WddsYkPRwRHP9XbpsbPsJpjtTI9ReGQd44qdPvuEONxd2i13OHmKpP6IglEU+BJiucjXNc7BUM1SXZmh9OhRjB7RtQxm1Un+jghMxq0uScX6TxvAheoXKzrY33v9uddMg75ex0=
    adminUserFirstName: AgCGPWrEKd1bfTGNQSV5uSwmjhETQOpb0sqQJAF0v2Cq3iaQYCd1JYviE6sRvtSmVCdSaXS9X//pxXljfZl2qKYbXMcwkZF7xcmW7tOxGdgzBBS+Ljp1kDbdYma5q7H4wN5FCQcCL/cwrJFGZpEspnsJAY1H8UTI4pWppmmHUuIBPakrK7UmYq+HkHuiTfD1Vq8A25alyqB86+KGxHQOkLC2uJIawOkKqf+ZxvAlkVzgXyvz+VUQB1c28URw9MqCsHMBiHikIem8Q/OgpOAiCAqCaZLRZUpAQWTOO9WTCTadSZt2bPcRarrj1yUjKbEwKtf6iX9wOdDl3g8bKGJxpyv5ZELIhSJYF7kuusw8vH8diNrg+/kqaHXvbl7nrQewv6TuMyyGKyox4HvxO8a/JClAT0GsN1rXxzXrgNwJ0mzqjOZDXCGlW6Eck/FGFhEvdAL6c4NBxxwe5UPq1PHMVF48ji+a5kZJcvUHxwzk7SJ1xSGcHVDno21oxpIcKlXXfci7kxpvWHbJ1l+tauD1/tuuHpKBcQDpDWRH4NAGGR2zyg3Bv1Wuw5uKacRZ94UGk3jfJqUVWn4nDwkJJlseF/D1DSe9VgqUb2pYm54F/yJVViT7IeUL9OTA4UKFy3rBZbiqT790QIy/wcI92K4aLK5ZUK8CmejcdbXwRxVKHaRaji3kitXUUr/A43DDiixH8rTu0DW/cQ==
    adminUserLastName: AgApxUFyW+ifok+VRpN4KjLT1D4ARNK7cj+PT2228UOyk8Tdm6K19BOwzYAEr3EjmEYwDoJa+ImWDrJ44XOOUY1hG3OkBOoo64FKQytBjzZKgbBXQBEGhTPyJq18C54+3z9k0GC5w0FbSgfxf5CyhZHI4+r46brp25f1rehjI3ZcNpGS0e718e9MPyfCEvwtAlkRMcxULQ0V1DZcaIntXdAhIvGXODEeTBLY3z/vUsCYP8g10tbZp0HjbdLBEyaWwmxOfQc4l8WGNwfwniP2VmuAIwIQHFElDdNy651+u427SKRtrpeJwhVnBRUohwyehfhW4Monp3b0NPfe6ijzvzoUqAWZbSnIwto/g4eAsQCZdegLKZAmRfNhddfLviAhrewJFv6Y7PGLGInP/3YkZPPVBjJmI06V+mIhDwmzMq+sG30SjFVceacngyDpasbHnKrZVmwt85Y9tHvuG+FajBJdQrHWmcKXn4mioIRztOMwcjoPy/rphMsH28iiXaHJrgZK/8sMSfowQfJ8T1vJgQ2ra8ZU4Vj4etgK6ZodXRnrFzHSLtx/VIvL6IzuPxVdJt+O9lWLCkjeiR9SjSFX1ktoN9Gq6Oaj/0W+unrS/BG9UYKxGPX9C2Kx4LIgMHGLu/PVY1Te7NHa9SnEaQZXxcyD4O7XmxnRkFxIpMzAJG0p7V4yd2bZyW2nuxZPs/oexbWlgYG3
    adminUserPassword: AgB4dZBf4LLqOD2w+s/0in3oLjOaBP9iJI4kzv43Oj+uqvYs2fEFYKlllVObF+5ESHJjdE4uTMy46ksWUVWiaSzLTmiHOIl26nP81ujDRdlzEegSYVNNWdMKaah2aE3t3jynVoyhg9xpiP3iFeCvrXJ/QZ04dZsnXW1cJilXvgSek1NooD6rVbs91Qq6xLX51UtkFEf6OhjaSopajNq+hWmEOwUNPGDQ6KAlDRNfmCmN15QW0zcVQqOizOO+Up1D0p126wB5qsvq/OTj7ScceTZEYZY5dH6DEwEkX7J9M+nGBdKaKx/PITMACX/lVAKuuVeCdVjF6gIIcvZXtKnU5ejfhI1WEom28aFNBiA6yWGwKnQXzaLwtcTDQcHBV5JbueWLW63aq/9mDDxYlXfLTJPp/bU5k99QDKymHMa2Yb0OmUjmOfbpICF4mLu2IBjWwLvk/1CBcLQ9nBazfREThS6OoD2e8UnbzSIIaIc7UrhgMJr8958ndsIzfQlGgjlsqQQbMDVSQ+UCVbh8gDLcWmYrWpTq9OShEXuZADg9g0BARFPzTudAvhpKSJWe4b70FnAxdhz8lXYefNmrQNskMX/8YbEVy5iYSANzKjRZMZkB3hpmRZ7Ek7YBVwSws4GGKYHWjlLvXd9zA137sxOv8AL44J0JOySd1LVnyPfqxdYR1OYoEt8IS11z0khAP0GgpRbAkf0WpzwVcx8=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: admin-secrets
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: tyk-cp
spec:
  encryptedData:
    redis-password: AgBzmAP1t0hkNF6QZOp+0/MPfer+sTwszs/10u2UDBLSjWvHogWTC62Kc6bGc5AMoh2GlViVCBqw9kD0wrGx1brsjQoXpuVFYGbhPvGfDnYa+RnJo4DVUG2ggkvJ2w+zyLHuC9C8fZCG9qnPN1i1ICfrmCZPvQe1jgpQ02jDcQy6Vxs5eGHqX1kRMx8Y4Nif31XOfgEuy04vldZ6VkuWBWAEVIu0RzRzFrb+7Q6KJ+RfoAw715Ntdr/VHWxo0kutavjlg5tnJFI2+98QUkqqv8GvyD6ZYIf2mVgVetz0zjwAPWeNapIslqRn12H8Ff6k1UUwZfMfjxQK/R0xY5+4o7M5r2Va/M9+AsJvTcQmmYHAaWKGpDH2mpLT2PmUeiTpQn2BvTQ1VcLNX0kx8It1JwFSUFl5rZi+oT0EcPcSiHRUDbcRBblDCMGVbTJbR3xsb5fn9xjbPLdYHbJkolOW0V8Y6n1dXTlyubUiPPUOr7vNRyoLRTeom3xVBtDSIIseQbVfh9pMqEIPdg83SfOn202qJLIRqd975ue+S6Z8GGMuQl0WhPO9akEleUzn5Bnt6R2FAEYpk5CwEKQnTWXg08zTM45dYYCEuma6oKjhzupUYGUxHakLlBHoknNfjqlWqS9S2d7GVsLpBH4EvW3EREyLTibXZKTo/ToYLjvUW2Fu/BHnBWGPsHwfL/BIkoleIOU1fBzEHy4liMnXlOc=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: redis-password-secret
      namespace: tyk-cp
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-cp
spec:
  encryptedData:
    postgres-password: AgAuoC/YDL6tWsH/2caW8T6khfLXed7lU5zxDj9oEpb8xuvtJAKmyuuqe4DUARBTUGp67LWZrq8tHx+da4mXazkhAP9fMmzXZk03XCk4FH7ndkaAfwCH2yvFy/GU1unXtOD5mwfq9qWMD9NLhomJcZC6JVEYNlcGrQFD68eKRleQYjafV4eKhELzuvw3nGao0J8xE55/YMYFOqyfSQYNA5q/ddceTrxQxsik5j6nx0s/Jix9KkLYjGPA77fugbd+prrGPE0Qs/tzUoAF0hhbLG3PZOs1o80+3JfCmz5fckSRqDYwasLrppEK1RO6Pxyhp7iixILAjDfrLmy/7z+G2CREseEgj3atOlnuw5JBnYLap+14VoUsN+2Hi8PqsJ6OaW88WxKc+km3zp/aCWx0hzU591YG2bbQiONWsg5w5qM/bMcp9GzCLrGfBrZCLh3bRGfMeQDfM1WMroyiDotRY6wHKJwUHOtD/H4EMaU51U+plWmddpWNeYx2egYV2RHhUnmmSJ6MQe4tuEllkbcJAeyvA+CrQdC0Ee9VWUtt12XjX+7aDb9KeRl9GzJUjUOoImyV+2HoAWJVIqx5NWD0xixv+39MCq5PGiwkGmb806d53ftoq00j8lzoFyHYvitlsu2ReOCaSq/GFBNBON7EencfNfJr4k51VZ53gDS1IY3EgVuTjR4mWwpwEVQhp2vN8Sn8FECwWRYjSMj7
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-cp
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: tyk-cp
spec:
  encryptedData:
    postgresUrl: AgAknY2QzNmk7pzW4tQoHHlN8mP9BGg2JTX5KrJSjBtzGHGY97El3wnsi7LMLMLB2RDn0LF66Mx0lLwxaEakKDMh02I+zwH2TFUQz6+IXWLKRvD1DSbCubIcUzBEcYCopT3LzKHbjzib4djI/osj9tip7roJmV+kB4oSY7IUVBnDtUX/2NRqADZk7MtJiA+unJy6K2e6BD08jIt/FT/Z6xZFtyod0qNbOZnRN18fqU+cojC2wWbjbgPaTjP8LojuxKzBalltkiQw1MMKP/18Su2mnwNtLLmqNu1L/mtLB+riBsf5MMJJ553CT/sPfXxswjZ9tNPU+VEKzbKNhfN5xyhh0KFevgxPDQ1VnmOOw3icRz0JZv6DiGBCSBpybIZ+G0bCBXCpu7SWSYNju9D+8keoDgg4vRniMh1ZOqjil8+3NbRjJDIHXR/lv8ozVn6EXys7kahnzV4kr93QvR78jIUB94dIuGojck+uZKvfKzMVscO/Mzg9TPwaaFcWAPToXk/s90asSXX/RPZvpt5DldiHbtbGPQM78+SPRIS1uGX9xzGJO3YE8LouIWkTR3kU4h5JW1ufkJ80/0SlCP427HPXV9Zno6xM+uVjdv5EvYupBvWehf6jf4FpcfAb69FIo44IzKPid+1ESU2xYFKxKuCxrJEtX9iu9jGeFW0RUuICbelylFozduexiqaDX3LdnrA9xOCEVaCNaD1v8R/45iirBqTfkfSSM/n4dOTqysLThh+r3aHfBTQBJRwasYoKBzPYNBWqdtk0hScI4qGM42UQUWhevOushoEFG5BISOm405MjRlCYV2b+3R7FjDiddUXVidSXQQ0qPKDLuqCmmO5U5Y3B3ff5OQ==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-secrets
      namespace: tyk-cp
    type: Opaque
