---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongourl-secrets
  namespace: tyk-mongo
spec:
  encryptedData:
    mongoUrl: AgCy0kLIZRnPDbyLa75ZyHTUw1KlqjXiD3BheFECkOe8mfoFv7tEyiGokBCF2zlqr2n4bU65wbL1LrekqlahjHKnmVfSU63fh3J3kJxLbwqylbmMxOyVgJm0pKPjpXz86iCregLyU0RfadeZfhA17zdAAjidKm9hP5dbrPFrnPMoPWkQFlF+OhdDqFguOJtPOEhs8uLUO1ArcWCst4N94xiK1BHSL08BqKrkCqhewsZ09g8RGnANB4TCgY9Fj9jCzAzgtv6moeXnri+fE2fsbwEicbx0qD0H9FmWr/EYAjJrK++X0f37OSuQtXzX9rkLZP9dEp8r9inDKGiMtck+u4QhKHqn1FJk653ZYYZFhqumJnn49sjpLngNsaQTFuZW2OWbUnLVG4+WPmJZzltT+QGf+gvK+8gLetzHLMubNJMhzkYshPlkACHM7uZMuon+EKdtdFmZbIzxFlMaaEVRiZlh5gwCuZd7T7N7rmaBvEYbExSbSUgOVcDlJw8gW+lnfaTzdxR4JHpye5nYO5D0V0rGtmh5ByvhZGqeGLWTE8uGXc84hJBf/HywkAkQX3Q+DvJkcJhWOs+s6ceR81pCYEkgzyqUsxy7/ADfuDgW1SzG5ZQKfmvcefH9GoPd5HfYrkPMHkgNnLregbi4QVrAmEqJIGbuvK3W8HqHMtE/oTqDPobrIRbfe8Y2Dp1NtFlYh48ySDrD+QdSrD5Bw/urMdmEFmQ3bqMl4eEjfhhd9VKWJIX9fQ6UGgWGSrN3vIUnpsD8kw==
  template:
    metadata:
      creationTimestamp: null
      name: mongourl-secrets
      namespace: tyk-mongo
