---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgAUxcSoZmMQVvm02CwFm8BAfZoCcPTsCV5qayhPl1xFuCHizPA/UwiiBnMUTDAX+0dWlhUn0mlIsUV52vdnyDUeHsvxx2NZk1RkNA4hljR7kqV1g2GXi4OedAqo/0l3qrk6caBO13rwnFm2iL2i1/rd7xbVNZIZYG3TA53xV46jwz9qaK+YV2uHl6iuSqK22NJscbsA4Ztkw+Nohrs8LldA0L2xEN0aJcpEHvBYzz09TxBcxRNXOeiOpsiZAMRdR4j+svp+a8yeNWR2aVnPuNHpMLa0w7rHm1oQS2PX3pR7ns0KkGoEzkf4GjxQ+suAWkrby1gzrDfMQuStGkT+ibqLiUw8zjkllfpJzaGdA8E0sXy4HHZwLcwEIcHHWZhPVN7G5wbnrEXXVS9+BZABgy9y1rL5i+/UUNjnlN3gom9GJu9L/7HWMUZiwwaoSSAzaeM3NXq1jpoNXm4SPxZtmKjfET7QFLwKCaROYBDjWfkdZhWMKvOBra1J88UVdvHr/8ue1RX8hAwDi37iajObw9E+s186pYuO8bF6/neh+6vnMc6jTXWM631h2gTGxmu1fvUbs6EvnR41ojdWN4AJ6lPpMC9dPnLgjkYZTv+S8ARJgCJMsWTK/5+hYAqBK5r+s79gt2S0HGS7K0N+n5ys9fYpGLHnnpl4AFuktxeSOSRs481cEUfs6uZ71UKD4O6tjkyRotwIrsSE3L7K
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
