---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgBFoHYgP3RPi5W+4ZJgGtB8eB9oXg8d9zV3Gzp/5BgluIofjBj7IxLailjxE4z++o3EuWQ3LbFuftdf3ZDe/BWZ2OBf0nOgWb2Z1EorGFRM6SVG9cBgsxcAZTPuPCw1OQvCJ3mx/QRigpDjEWhqQ0md7amkcNIVwk0/5jngSXSp0Ti+O1eFd3LB1aD5qVr+GJkyHeu64Ni5QdYSkzmm5G1tMhkgIDQuuMNmCT0uqU0XsxE0ZqkKfm9NM0O94swrjRRFRPfvIk6/PcbUOf/lr1MLTmydr9jFVjMLSy1MXGbG27RiPF1dLb3+liFnti6f8EPI1SysAfILwrsl8ngPSwmHjloYjf7BFZsedWtLe5UA5OxIXcrV1pYWfvRmydxd+idoSlqyrQAnlz2CyVHe6KjqKuckMcLjg1jKOZqEs4awe70AJP6HCFUOaU04rD7aGeSjizM+nGcum5vXbrGxGOLnP+MvkuFCIFA1TC4YCjenn09RiwaQj3+RDra8ie7Z43rBQNU1mc8WedhFkKr/39PrRJ0QMisqculy6DbPUKt5foFL63l1pXGepkWH0LCZEiZGkPu0w88Br41KDozIYtqx+sDMAAw6LueIoB6GjeWicrzQaZj1t1YnWbWe9iV6A8PqFd6vY/42U9Sc/GjN3gmBITfqeSB18QpxfONh4wjglMJl8BBWMjwgXMtXrihT+dBVhy220wzRCANM
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
