---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgB/rQQC/Z05/4XkgG7sTa7Q2wHyJ51j1nEyp4DX1E3FPx6TyCQwY0Pr026fHGnfvI5ytALuCm/ZvnAewN31A2C7rmgNu681vW+Wou9wwIn6xsTBDBNI8lBkcGkmZ6ppzPJ8Em+dHaOg+JrrdKwOD391sw05nw+9cauh68WjOWQwMTmJg2k1Czuz47wEj8GhAqgp6WwMcdAJYOfDDbpNbBBcacSwX3fT9H0i8BTJ5m/Dd8agmkhgILnPM+KswkKq79FISmxOPZsCBHctCRf104O99aBFk1O1qf2/mqyTBZbCe3/OyWi5ZWsLi50dO/HgtrtY1BydKn0PaApFUfwjRLFExUalPvfyIdx3vtKooivp03bEehWNNH/xL0tCBEbOXCGX+pHZMJr6ZY392v/+QuZbPUmVp03sVjo30AR+GyhYaEz8UfJKZ5xpBBjVSVFWl8Y+bwj8hk8qbHe5V/DelWmIiVARpsLupwk62JJMED+kClypQm/ZpoFIdrWDgNs9XUunnZ2Z0WPA8hhkJTBokAmoMiZRUmpH7a0rhRhhY6ZJaFNDTVVcwL+xs1DqeFyyZ1+wL4AF+WCymOWM+GxmBoBbSb1jJ7fWsgTm0N0fjNT+7wRb/zWtQKDOC2xNpb/gXuyZ005SxownkycHHleCoWAPyfj+wlw8HXUBuRHj4Yrop07jFu98TLIwpBGkwvEpU945sGN/uxdkm6P/
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
