---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgA05WPm3gVVHHDoa/s9tBwLfrw1y12hmecMqQCYZj2CIykAwffV+o2dklrZUxN8VI2+SlfU2sfyysvtetfHwQ0C5eoSIO3i+3XQa6+GYTcVQepu+zyhP51qnoXeSU1QWpj0Io+Zh/DPmjW/eU3sUl+OqNTIw9RWN8K8Ar7aIXBwknTJy26f7M2gpuUuCnJRUGzFQV0VHFsGWKCyFqyhBV812SVpMnMVv1hR86/OGlNUPGhSuA2MJhpnicTqone8AacMjh7ijgMv/tI+RDKRb3Yxq5Z7f+GQTt6b8fi3FnSL9xsqXzcTVlq3rYizA8DY6tNJWUzOjKYOzjSYM97tryiDZJ0zDxo/bR7gTyZMd9DwNgTEhD0XDGN55G9qhiwyOHJ3utPDmMCruZiiWaL/G7G4HVVUtqCj3efuBXfH2ybx4qLQT9gibQTerNX1Vd+hv9uSdXuNi7zTp0vlvoa5WcQpdMkinr9Bqd0HH2JjHXm8Q9RYNXM1SMU+qRjlMTJWGm83bi3PeZzpfcL3qEaceXM7ghlb13D6e/Rw+P8MN5TJEX/x2lO2zgzNWr0l4CkqlticOkID8cet5L/9Uw88AyjuDTcMujtbhE6tqnG5C9R1DnGAkvgzYhbAhP9VhOQdLcc9m1SWk8A1gdWUnug722o0qbcW2jASR9aA+6qEe+wLTltdBPqhnCVwEL3Qw/h+zxYZwl+UHVsPB9YM
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
