---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgB3hEFz7t02nNbjbGeZ9eG+HdXDDBmJU1qIvmlXm1QDAtqpY9oEK/BuMBOznn/3L+0zaUbLOD9xvLfnF6S1mhxb5U94JEFQ3qZqj5Lu7BVNDA49TAx5hJk85s7pKuZh0167Ks8HE4kWufHeDAPzc6fazP3P0TFptzXbbeYWOYmRqtApepIhCvvu/BKc3etk6rixrsce6E7jomD+c/OLOZlVeRXoG+NT4o9qCDTMeCn82pKfmdWxCR7f+M7ZiON3phKgTogrWHvrJ0umq6gDpWM4EhPaj/JuksCuXaq56IT7bvbKoFdEbbIxK+g4FyYZ98dHTOsJJHJeDW3hjUFwFgjZSekctnvljbuCoPWOy6BJmlIFKL3cArtvDE0wr40MttaimPcwDbggPVPKQDl95fzSCuvGUI58r3skwiDGTyU6+82vFhxg3B/fOgAKe2oFH+q/bA78MOXGXNOYMG3XSRrsUdhSLwhLMd6kuv9c6ipXehs44aWH1cBjcHttXi1zF0nHuR3/zVT2/fFzhTYQPk3wjijKJMcwm+jDzcOL2LVSZM8S4HNWqgXSbcf5w0WMzU2j9uUz79YRSlVrNeWU3eth/dUBOZKCTxNvpKkQEH2snfuJiaZIxRuMDtdwTsd6cGm7JACwcbqajO73SpYYiHvbkYhs8zun/3mKc9EMyJbuJXfmq8CeZlu+QxXOl6xb6+d2Zr1C6Z5iBMFX
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
