---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgBruhUWwluCkqmJpdvyG16KSrOEnygqnIEvhLt/PeO5DjoV7/L7sE2Qm+k3KnEe8U8nIp/y2Dki5Kr01+KCdhy7O7l1HqvOtco+gfpvGozEMSnc+7C42hMlqQJiNPDUzv4vCehnGIe1mauAimz02fJMAl/kTomp5JRQGOsxE99NZ/T8zMOUDe27K7E5PJcRpRgMCTyLa3bgg+VghyrvNQLkgnvn4x3alYZKQH/E/ucMBaJPQNSEqq1KNpwMHZJH3Leg37/2CxBSTyAIRjMZt2gwSFMJjuDUjpIW7L425bevsOq6saMp5m6T2zNTJv2TRFwnXKdA42lyCDujjCP9Z8jmS78IL0j4zXLcSV379fj5kxm6m4LEW1BtkQ+/mmDxY0RrY0PzJH5eKUGmRjvX9ysjZuCUfxKQ2zZyWXmeoV0OQwQwtGMWqaEen26StL74zl9ECAwjDbhYVZF5pdR4dk2X22iHsLHkDU4cNen/d9Sfs9PDpXBNGt+drK5YuoTlCtYknAWp+AyKMbTysz+uXlz0kJde4Im4q7LQSUPl2j+DXM7GP1aEGhrSThkuy5ScEB+UPttem3ndQKhmRmaQcgmQZb1tJhtYad9DjGfTvSNxvcGLxoeAK9cULuNVgUUpW1gmyYzq8b7f0ANT3VrqHZYRBFMjN7Yo2P4Scvy/rlSjEAn78jxgbMSdggDixcGl4H23rAsd1Fmu0BLg
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
