---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgCOsfsm2pul8Zdyg1vgj4wI1gXgIT7MIyoyap9h5pIdQ7hQ77JPRcEYf0PZcejGkNOBM13nRqH2MG4vV7KI3Vnz8rxAigOxwv9k2B0v+zXzFvW0lDq1C2iOZVtqKCqmCqmcGxnOICmmLleiwAx6bmFtv+qWpEJxeOiPcL+SL1FpEs1YbN6gL7CNF+nLAGhlA7SK5RfovsQoSrll3A3cdCB8r0HfVanwsM0VxkWwDk9Ug3BqtnNIyZjQTK60zPHZ74QKqFwD6oCsR5XKvb8PNDfJdGMW5/tv3GoVRbPYW7fA1WR+lXaZU6fqnDCn6HeSL+nsqc85vxsttxsY7xsZ4Nnt7B2r1xdMmy16hFK11Zak7sj5hVuBHJuN5YwVy4DLeADJJy3cy+X/j6dOI5jX6CTPhli7esloM6G6+J0VhjLvWDql1oiAqjf7Tabk4xhJxpSY8cphUeWOxVAG0qbuxhrAQsgR5xiJqVOt35bM11GlEIFQ1AITWnMW8fNvtVJ9zuDSQ2/mDZCXbGIHEDxiGnhOK79Nav9r7N/tBXY3SmSeNiTMunbfjqJJ3YtVdBoMh5TQtFWfeLJx1TIuXm567AIO5TPUZdL7am8jr1yASHyh1RqvlHh7qTDSHKyas1CusCRKY33UnXWkySGjdy9WsRIxoaQRJZR3XKZv1qxdLjbMLfzQmaCsSQ5IwQF096Hn3QiqTPAcGFKI2gAG
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
