---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgBOtsqUFPljHmR7xH92y7V3N/foH9bbMJegd1Whs30fnPwXyalCXZgfq0Rcq1abJlnGcbU1SBFDKFVPmbkDECRF3Ch0MROjST/F2I575v/XmO23UOz4lHL15qNcCYba2xRNfDClsINVFnKNG1gE0EIKVwCsjj1YPfJlI3TgfU7BNYAyH+H0EXyql+avrNRA9SEadXP6uedPAoQ1JuTLIFPZBBjkjPQ5iCphnk1we1EvsmBpqhtLG9yhhYDoLuRJN/hO/kA1Fx09flyjvJEbhCiZectVqLtn8Vv1M3c7e5tl+a+AtcnUlP3A+NlO8hF6g30IaJN4ZlxzixVDoCL50zuGQL9QNWML75fAnkDg4qkthcBFuTql4zr/6UeHnhdjJZ2RnxWmaGsA2VES3bBKH41P/DnDSGGI7r+utM7cAa0KPzFRQdHw6sj0Fn/jjtcXghjM1te+yCu8fZDFqK6efvMvU/pruKbfPt3rOZokxrY+mRTVz/0VZ0EnV1AQ7U3kSfgDq5JmgnoeWyiD+JCCPWPwsgeOeA/RuCnwJt4CIJrAaHDXfPW2Q3DxvJybkVaQKL06zjIErfhsFgBw+6teZteVcOjjzOSFyRy55pw/IgPmNKwWDNTdvb+4y+9U/zwUdrbSb1I9C61wlBkFbAykI59jnICmuTFRWcmAylSPBliyMujNI+327c212NaxQm7QKBeI7qMKiaybvpun
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: postgres
