apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk-policies-app
spec:
  destination:
    namespace: tyk
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/tyk-policies
    repoURL: 'https://github.com/caroltyk/tyk-argocd-demo.git'
    targetRevision: HEAD
  sources: []
  project: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
