resources:
  - ../base/
  - tyk-postgres-application.yaml
  - postgres-sealedsecrets.yaml
  - tyk-stack-sealedsecrets.yaml  
  - tyk-stack-postgres-sealedsecrets.yaml
patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: tyk-stack
        namespace: argocd
      spec:
        source:
          helm:
            valuesObject:
              global:
                postgres:
                  connectionStringSecret:
                    name: postgres-secrets
                    keyName: postgresUrl
                storageType: postgres
              tyk-pump:
                pump:
                  backend:
                    - "prometheus"
                    - "postgres"
                  uptimePumpBackend: "postgres"