---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-postgres
spec:
  encryptedData:
    postgres-password: AgAr/I4OPX/4y4HNOwCOw+aYp+B6axbhPU3ydXtLupnrrPf9VsbcZ0S9wdXM5J5JA0QS0USWuZ3Xrle6RfrraNDxAu/TI4WTj/dV9fbWkJVa/rQHwu9MbOnMiLGpxM9cuWGgtS7iB/LjKUdCiTiDGMWUGhP4oP8akzf+E1VB8w9B4BH/sG4sCP1UcBOXkZoI+YCO/9Xmw8okA239rguI/kWLtOXorP2mpQMuVh20d0brlZW5IpqL0v57lfu2NjnyamJW1U67xFge9Q/kuW4lc12mQ7ilyLYABZGmNxuF/ulkKGPVzSIg4+1ktTBPDDxFs9CGIPVYH1F+o+aBRQMY32bQP1PUEoAOt4ExLQhkr+r2PQvC1f78xP8iBYfwqNpr9cNGkbTg67EG2gxGjPUNPoIFYATikn/S4pxF+Q2NvWkrGyJJIm53F1vsabA4dbJwHxCy352rq9uRib7kZUwjjc+WO636e5Ds2uVJRJY36qUDHLjIu43f4ZiuqN51vchAN//L2WrSulin2nkACeSChTrBGJc2WcMc2CyKB+bI2MMoJdMS68qV70kSI6eejIR9KEPMh7G9JljEzBXGDgcqp+EbAoWAxGm9aYQAO+JtJvuyltT7CTuW4wtHXpyyw8XWtYCfnO5SWnL/P8gWXXpZFqpDq3smIEARg3Siqo/zOl5MdxdqyclOBZFOn2Br0YuHAzeBUwE2dn3kVLwf
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-postgres
