---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-postgres
spec:
  encryptedData:
    postgres-password: AgBZj52/sNpfq9uPD3F7fUcqTKptVTf8AMKi0y62rrAq4+CmjG94ZVWr4NaVCQ/Ape6alDtPEBj8lnGUoLKiyRuWDdvti7lwjsXOHN9qECWmBSZZQN3v29or6G5gqMoI7LXRqmMHTqpvggKWsgond3AcgU/sDHEqW/1Xvt7JaTe9/t7BMdA2aub/1J4AIC3oi7PGvfZUa05DoHFcZie55n0ffdywjjyRtH/aebo1/JAkIKcCKtrlx96zi84MFx4wcaGdHgHhAuQEIH+muAiqHBXwxHLH2N13oFMJsOI6mM4awCJyAAFZL4m6XzP78pY5HQyQLYjmifimyCetUp3c3O9m+AIIgq/LCfZGJm3+33rTp8gpIm/TpXRdOFpCphwUoRUeCMG9iRDmNHfyzrkzU7OOX6tzqntursVf7ybe+1m+ILUrIs0PAQa/+NIeM+86L/yy/QVpXhuXifXro5d80UkIy+zw2xIFu1TrCgftd+3aEmROxep+XH5onGSBLUSC3wZoNwNU2++2xWqvrOae3YYIXto7HLoRUj2MhkfSsvPQ9VQrggT1WpTwBrnIhXtYj1lwZ9MmAEQf1leTdXXH/kcPtRzqe2ZXxOLU5IExhBBYZ+X8sjPBZe9UhmwwNyGvLv6c2MrJyB/Jd34+zAieYLTl5cm8LPOyKMbtSV2qH6fu20osc6tOjNLI0uqCTLv44li39Y623wjt0whA
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-postgres
