---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: tyk-postgres
spec:
  encryptedData:
    postgres-password: AgAvLmIfyx3O31EEV5ydkpBR8hjqUHVbmUDldsudMe0CDuG7sF/qpAY3EY2Ishh2TJdzBiS3JAXUhYFeguL1h2shOom2P6jl1oz7isJ4stp4QIhv2ucsDLBDZoN2DpvGT2ZaXQNQrZppbXwXEBip/WhL8HEqkXbKCNYBXLb7jjPZpbGYbG/8h7vK8nDPCv+w2tZUWFVYokyncMFz9roo85sXFburz4dQg99c0Dh2mSuZvdqXMLqG08BPh7M9fkf3bs5f6ndni94pYpUOCByTNc33KUOmNb/582WaDoboqFmHtxt3nrkt8M2//Vn4fkfAXcA7jKVIIyW3ng4JM7dDQN0G3VNRv3o/nfpia1AKPC35noo5j+482yPw9m+Y9fEiZlUAxqMC3VL11WfeLRyCzg4NiBxwzXVrwwnzLN2+6Yzl/pyPgjO6Y7F/P4T2A4s6kcoByz1i8S5C6mzz4jOgDYPZjJxbiE4/2i4IFAspzVnMe/WOtAC6mpqv/mUzeipGJRoHI28sSUSgaWurVtqXbFEj/CKl9JlPxkuSzUlk5J52yM4sWE2NF6U4eSFNH8+W32mO70GQGLpmGayTnNpNuiW0ibADkaLP9xtxyR4gdlQ84W2zyJigVIgIDerWFkEEAE+L0yDrd8HP+/anK9xs9SRH7YkPJUb9qBC7BBXyy7jvz0095uh+ZZSQ07qlbm8qH8gmDcdREBkVMf89
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-password
      namespace: tyk-postgres
