---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: tyk-postgres
spec:
  encryptedData:
    postgresUrl: AgCOVBZwtKqlE+bbIj+sJrs4Xwc5lW46RF4yBUyqbeLf1zp0YByieBjHx0BR+vpe7zYny6e74dZ4PMiXYghvh377LU/384h4oDjPwSgV23c0u1HfEYVXq6RWnLeBO+j8knAPicHvZ50R2v2IVjJ2ROCGROe7oNkZxMWbTsqTBJwtuFRKNylHFSxZHmw59mcq2VuW9+1r3WYiA4sRtzbX/kbKV46K9Tx0tcnWGIcVKclUByvOaKh2EHErvJMuEHmddTQFx9desBSJRYKp0ah8r7Nown4oGrHQuhcHL3dTENhOCydhZfIV3ibHUP2VMdzFZt6h96hZXXvecW6vYhVajo40xSzDCy/QnJOwxG78LHhP0nIW3XTjRw0zzo/MATOSptW9hNZtPcNmJb+jpZCt+DjHSOIXvS82QeW48UxrJB12Ppv3ysHzDUC+fuhu+Nzc8Wr9xSHyE3Rfvdwws18IJad5gQUUFsTD+eLqc2uRTzmmUMBsrTrvFydh0zSnwV1pAQfURN3nVInJFvl4dvaH8tr0qnQ7Fv0ttwCdtz2qByY4X8aS2P/qoPj9SQ177qP8FlIyjXLQ27UmoK18ld85bh1hPwo3ogmlzX57bbMRLqs74m6aq4i4TZFEDp9Qw3bWThTV5GdN5bFOWONrAWUkC75vfL8rAANuSUcyn1H5fbnDW9qAQVpvDLbZOhbRaa6e+nvoyy2NgtK7N25ijiGkrvA+y240JlDk01VSyysWTGAsq90dk9rRUs8ZRVvyWf/6IRO2DQYqTMc7sMEClZ6biGLSZViGHw+uHAHDvhxRSik+MLtiOCLH46Ebha2144hC0LRAMBtsefSiNkluaA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: postgres-secrets
      namespace: tyk-postgres
    type: Opaque
