---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAtXSDziPPJVMEtFRLFGbqosUrqN0ZZmIHolgw4oOmmbgfP9+RoxAnKI32S1Q9iAirSlADvk1id8Y648i5418+Yir1GYCEHorKRbu+H2sQEdlhuY2KeiMWYbzYCGAkvB05dzFtcXl0ugN6vOir7m+akeTMKPM3D8nIA1f9VMXwH4U2nGtXoUQvVtNFsorK9qXjiRlfcBn42s7ueiRMly9AaFVXdwCMotF8yPs8xN2mMF4UKYuiaEeGrgqxwkJq/ZDRGLno5Ebh9DJdKUhJRgiV8iQMODcDtJG3ELdCTIkNCkus2Neo36RJAvuOhV8ieKAfOQkiAwkxkSS5zVYVWyGRuTrleync2eQWZl5L12B9pwXqjJSyQD/Vkcd4DlL6IA3sK5HTp+chKBnlzsZuB5TJu7WKGaD/8pZ8RbAI/AHNemxOTHk3PfrY/B60cbypl4+dB2Iy7mmVbAy8/FgwqSr6gjeteeQHgtgq7BOiDFWLbJEeWUV9cvpOXrd0JuFz49DQKHwccdykuoHSAmKN9KGPzJKLL8wmeYQFJtI/q3i4qX28BjU3HWkuDqwipndIU7ih2mFbzFCEYtHZDh3bxSLIIfxQFJr0IwcAYC6ibjsEts5TNHAFUZCs9HMv+zqkJFLuewCE3SO6F0WD8VDu25iNHqRwJ3GwWne5rH5FT0VV00I6aUfvRmrnXoS2Rx8S/yU8vvg5fCDPcr7WaO10=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      creationTimestamp: null
      name: redis-password-secret
      namespace: redis
    type: Opaque
