apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-oss
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.0.2
    helm:
      parameters:
      - name: auth.existingSecret
        value: redis-password-secret
      - name: auth.existingSecretPasswordKey
        value: redis-password
  syncPolicy:
    automated: 
      prune: true
  ignoreDifferences:
  - kind: PersistentVolumeClaim
    group: v1